### ISSUE TITLE
Problem uploading files > 1kb

### ISSUE THREAD

**Issue by samolapraga** [andreafabrizi/Dropbox-Uploader#176]
Hi Andrea,

First of all, i would like to thank you for a script that i found very useful. What i am doing with it is pretty ordinary, i am uploading to my dropbox account the jpgs that motion outputs from an ipcamera that i use. Everything worked great, until a couple of days ago when i noticed that no files were being uploaded, and i noticed that even when i run the script as root, i get an error:
0.14
 > Uploading "/home/pi/ocr_pi.png" to "/RaspCamera/ocr.png"... FAILED
An error occurred requesting /upload

tried to run it with -d so i could trace the root cause of the error, and the last call of the API returns code 52. Could not figure out what that means, so i decided to contact you for help. I have sent the log file with the output of -d to your email address.

I also noticed that this behaviour only happens for files larger than 1kb, as the others seem to get uploaded just fine...

Thanks a lot,
Alex

**Comment by andreafabrizi** [comment]
Can I consider the issue as closed?
