### ISSUE TITLE
-e problem in mac os

### ISSUE THREAD

**Issue by zzgary** [andreafabrizi/Dropbox-Uploader#195]
I have no idea what's wrong with my mac... I use the same script as I used in my linux server which works fine.

The problem is that the script will echo the "-e" on the screen and it will also take the "-e" as part of the input... 

For example, the 
```
function usage
{
    echo -e "Dropbox Uploader v$VERSION"
    echo -e "Andrea Fabrizi - andrea.fabrizi@gmail.com\n"
    echo -e "Usage: $0 COMMAND [PARAMETERS]..."
```
will output:

```
$ sh dropbox_uploader.sh
-e Dropbox Uploader v0.14
-e Andrea Fabrizi - andrea.fabrizi@gmail.com

-e Usage: dropbox_uploader.sh COMMAND [PARAMETERS]...
```

and if I use the list command:

```
$ sh dropbox_uploader.sh list English
-ne  > Listing "-e /English"...
-ne FAILED
```
and the same problem happened with other command...

the content of `/tmp/du_resp_debug` with the **list** command as follow:

```
 HTTP/1.1 400 Bad Request
 Server: nginx
 Date: Thu, 08 Jan 2015 03:52:44 GMT
 Content-Type: application/json
 Transfer-Encoding: chunked
 Connection: keep-alive

 {"error": {"path": "Invalid path '/-e /English': bad path component 1: ends with a space"}}
 ~
```

Any idea about that... Thank you!

**Comment by z3robyt3** [comment]
The problem is that you run the script with the wrong shell. Don't use sh, use bash instead or make the script executable and run it like this:
```
./dropbox_uploader.sh
```
Bash has a builtin echo cmd which supports the params -n and -e while /bin/echo does not support those on osx

**Comment by zzgary** [comment]
Oh!! That's the reason! Thanks!  It works!
