### ISSUE TITLE
No timeout when uploading

### ISSUE THREAD

**Issue by bpsib** [andreafabrizi/Dropbox-Uploader#197]
I often use Dropbox-Uploader to upload large files but it occasionally gets stuck when a connection glitch occurs because there's no timeout set to curl. The only way to make it continue is to kill the curl process. This is really annoying.

EDIT: I have just looked on the activity graphs for my server and shows the outbound bandwidth had slowed down from 25Mbps to 0.25Mbps when I thought the upload was stuck. I think I may had set the chunk size for large files a bit too high. I am not sure what went wrong. I have now reduced it from 40MB to 16MB and will report back if it gets stuck again.

**Comment by andreafabrizi** [comment]
@bpsib, is not possible to define a timeout, because the upload time depends on the upload speed and setting a timeout can cause problem on slow internet connections.
