### ISSUE TITLE
openelec raspberry pi

### ISSUE THREAD

**Issue by spoutnik16** [andreafabrizi/Dropbox-Uploader#198]
On a raspberry pi with openelec, it just tells me "Error: this script requires the BASH shell!"

**Comment by emcek** [comment]
There is no bash shell in OpenELEC only simple sh from BusyBox. Take a look at: http://openelec.tv/news/22-releases/139-openelec-4-2-0-released
> OpenELEC is not affected by the shellshock Bash bug because we haven't used Bash for 1.5 years. :-)

**Comment by benjaminsherwood** [comment]
Assuming that you have a /storage/.profile file configured (which is where
sh looks for it's equivalent of the ~/.bashrc config file) and that you've
created a valid, error-free /storage/.bashrc file, you could try:

*# cat /storage/.profile*
*SHELL=/bin/bash*
*PATH=/storage/bin:$PATH*
*TERM=xterm-color*


*# exec bash & source
/storage/.bashrc(Source:
http://raspberrypi.stackexchange.com/questions/17016/customize-bashrc-in-openelec
<http://raspberrypi.stackexchange.com/questions/17016/customize-bashrc-in-openelec>)*

Specifically, it's the last line that you're interested in - "exec" is a
shell built-in and when you specify a command (in this case "bash"), it
replaces the shell without creating a new process. I've not had chance to
test this, but it should allow you to use BASH. I'm assuming that OpenELEC
still comes with BASH, even though it uses sh. You can check this by
running:

ls -la /bin/

and taking a look at the value for /bin/bash. If it's just a link to
/bin/sh, or to the BusyBox binary, then you may be out of luck.  If this
works, you may need to look at creating a basic sh compatible wrapper for
the dropbox-uploader.sh script.

---

Another thing to look at is that the start of the dropbox-uploader.sh file
has this line:

#!/usr/bin/env bash

It's possible that you could change this line to reflect the location of
BASH on your OpenELEC system and that it would run as a result (this first
line tells the script what shell to use to execute the script) but it
depends if there are any BASH-specific non-POSIX statements in the
dropbox-uploader file.


*Again, please note that this is all untested as I don't have access to an
OpenELEC install at this moment in time, just trying to be helpful :)*



---
*Benjamin*
*Email: *benjaminsherwood@gmail.com
