### ISSUE TITLE
Raspberry "-s" not working properly

### ISSUE THREAD

**Issue by EpicLPer** [andreafabrizi/Dropbox-Uploader#204]
Hello,

Today I tried to write a little bash script which executes every evening. I tried to use the dropbox script like the following example:

./dropbox_uploader.sh upload -s 'PATH1' 'PATH2'

Once executed the script will work but simply ignores the "-s" operand. Its uploading all files but still operates like there would be no -s at all and just overwrites the files. My Raspberry also reports the following once executed:

readlink: fehlender Operand
„readlink --help“ gibt weitere Informationen.

Translated to english this means something like "readlink: missing operand" and "readlink --help gives more informations".
This seems like a script issue and not a Raspberry Pi or setup issue. Correct me if I'm wrong tho.

Thanks for reading!

**Comment by andreafabrizi** [comment]
@EpicLPer, tried on my raspberry and works fine:

$ ./dropbox_uploader.sh upload /etc/passwd /
 > Uploading "/etc/passwd" to "/passwd"... DONE
$ ./dropbox_uploader.sh -s upload /etc/passwd /
 > Skipping already existing file "/passwd"

The error which you have reported seems to be related to a different version of readlink installed on your raspberry. Is it part of the coreutils package?

For me:

$ readlink --version
readlink (GNU coreutils) 8.13

**Comment by EpicLPer** [comment]
I have the same version as you do. However you did not include "-s" in your command (or you forgot to post it here).

**Comment by andreafabrizi** [comment]
Yes, I've included the -s option on the second line:
  ./dropbox_uploader.sh -s upload /etc/passwd /

**Comment by EpicLPer** [comment]
Ah, I did not see the second command there :)
Well, this is a weird behavior on my side then.

**Comment by andreafabrizi** [comment]
If you like, you can run the script in debug mode and send me the full output (to my private email pls).

**Comment by Zzanne** [comment]
I noticed that when I precede upload with the -s I have no problem, but when I follow upload with the -s, as EpicLPer did in the example he submitted in the beginning of this thread I get the same error.
