### ISSUE TITLE
info gives wrong info

### ISSUE THREAD

**Issue by wrinkle-wrinkle** [andreafabrizi/Dropbox-Uploader#206]
Regular Files as posted by Dropbox matches the Used, but quota and free are not the same.

![db_space](https://cloud.githubusercontent.com/assets/11094481/7030089/c7548e42-dd27-11e4-967f-1081a2ed3bf9.png)

**Comment by andreafabrizi** [comment]
What do you mean? Are not correct?

**Comment by wrinkle-wrinkle** [comment]
nevermind, was being a derp
