### ISSUE TITLE
Stat issue on OS X with GNU coreutils installed

### ISSUE THREAD

**Issue by dchandan** [andreafabrizi/Dropbox-Uploader#207]
In the function file_size, the call to stat for OS X issues an error if the stat executable is not the default OS X stat, but GNU coreutils stat (installed through Homebrew). This is because the command line argument syntax for the two versions differ. I have fixed this for my case, but may I suggest the documentation be updated with a note to OS X users to change the relevant code depending on their version of stat?

**Comment by andreafabrizi** [comment]
Thanks @dchandan, it will be fixed with the next commit.
