### ISSUE TITLE
ZSH support?

### ISSUE THREAD

**Issue by N4M3Z** [andreafabrizi/Dropbox-Uploader#208]
First off, thanks for writing such an excellent Dropbox interface. However, I do not seem to be able to run this package on zsh 5.0.7 (x86_64-apple-darwin14.0.0). Are you planning zsh support in the future? If not, where exactly are you using BASH specifics and could we as a community do something about it?

**Comment by Heart1010** [comment]
Why it shouldn't work with zsh?! What problems do you have?

**Comment by N4M3Z** [comment]
I am getting:
```
Error: this script requires the BASH shell!
```
I am guessing this must be some use-case issue?

**Comment by benjaminsherwood** [comment]
Try executing:

ls /usr/bin/bash

and checking that there is a link for /usr/bin/zsh

**Comment by N4M3Z** [comment]
Yes, there is both `/bin/bash` and `/bin/zsh`, however I am prepending my `$PATH` with `/usr/local/bin` so that I can use a newer version of ZSH from homebrew.
```
> which zsh
/usr/local/bin/zsh
```

**Comment by benjaminsherwood** [comment]
OK - well the dropbox uploader uses "/usr/bin/env bash" so it will use whatever bash executable (or link) it finds first in your $PATH - if you echo $PATH is there a bash entry? You may need to edit your $PATH to remove the bash entry, or link that bash entry to your homebrew ZSH at /usr/local/bin/zsh
