### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by macosxservice** [andreafabrizi/Dropbox-Uploader#210]
Hello,
First, thanks for sharing such great code!  I have this working perfectly on a MacBook Pro, BUT for some reason, I cannot get it to install on a MacBook Air.  It looks like I'm having issues with:

 " > Token request... grep: /tmp/du_resp_25786: No such file or directory
sed: /tmp/du_resp_25786: No such file or directory
sed: /tmp/du_resp_25786: No such file or directory
 FAILED"

I've copied and pasted (deleted key & secret for security purposes) my terminal process below. I'm trying to run the program from my usr/local/bin (same place it's running on my Pro), I've also tried running from  my ~ directory, without any luck.  Can you share any advice on what may be the hang up?
Thanks so much!

$ /usr/local/bin/./dropbox_uploader.sh

 This is the first time you run this script.

 1) Open the following URL in your Browser, and log in using your account: https://www.dropbox.com/developers/apps
 2) Click on "Create App", then select "Dropbox API app"
 3) Select "Files and datastores"
 4) Now go on with the configuration, choosing the app permissions and access restrictions to your DropBox folder
 5) Enter the "App Name" that you prefer (e.g. MyUploader283571031430936)

 Now, click on the "Create App" button.

 When your new App is successfully created, please type the
 App Key, App Secret and the Permission type shown in the confirmation page:

 # App key: xxxxxxxx(deleted for privacy)
 # App secret: xxxxxxxx(deleted for privacy)
 # Permission type, App folder or Full Dropbox [a/f]: f

 > App key is xxxxxxxx(deleted for privacy), App secret is xxxxxxxx(deleted for privacy) and Access level is Full Dropbox. Looks ok? [y/n]: y

 > Token request... grep: /tmp/du_resp_25786: No such file or directory
sed: /tmp/du_resp_25786: No such file or directory
sed: /tmp/du_resp_25786: No such file or directory
 FAILED

 Please, check your App key and secret...

**Comment by andreafabrizi** [comment]
Can you check if the /tmp directory exists? If not, you can change the temp folder location at the 35 in the script.

**Comment by macosxservice** [comment]
Hi Andrea,
Thanks of your response!

After some tinkering, I found that my permissions on my /private/tmp/
(which I guess correlates with the /tmp/) folder had been changed to 755,
but needed to be 777. After changing the permissions of /private/tmp/ to
777, the install worked like a charm again!

One more question, I just got an email from Dropbox stating:
*"Deprecating the Sync and Datastore APIs
<https://blogs.dropbox.com/developers/2015/04/deprecating-the-sync-and-datastore-apis/>*
*As part of our effort to simplify the Dropbox Developer Platform, we're
deprecating the Sync and Datastore APIs over the next 12 months. Read more
about why we're deprecating these APIs
<https://blogs.dropbox.com/developers/2015/04/deprecating-the-sync-and-datastore-apis/>
and how
to migrate user access tokens
<https://blogs.dropbox.com/developers/2015/05/migrating-sync-sdk-access-tokens-to-core-sdk/>
from
the Sync SDK to the Core SDK."*

Do you know if this deprecation will affect the functioning of Dropbox
Uploader?

Thanks so much!

**Comment by andreafabrizi** [comment]
@macosxservice, Dropbox Uploader already uses the Dropbox Core API, so won't be affected by this change.
