### ISSUE TITLE
Faster upload speeds in browser than with the script?

### ISSUE THREAD

**Issue by cboettig** [andreafabrizi/Dropbox-Uploader#212]
I seem to experience substantially faster (10x or more) upload speeds when using the browser (Chrome, on the Dropbox website) than I get uploading the same files (~400 files at 50MB / file) using the script.  Is this expected? Is there any way around this (e.g. curl header settings or something)?

**Comment by andreafabrizi** [comment]
Hello,
probably the speed is limited, for big files, by the chunked upload behavior. I mean, when you use the web application or the dropbox client, they keep the same connection socket to transfer the chunks. In the contrary, using the core API, we have to make a new HTTP connection for every chunk (with the related overhead).
What you can try is change the value of the CHUNK_SIZE parameter in the script, increasing it from 4 to 40 for example or more, to reduce the number of chunks per file. 4 is the recommended value by Dropbox.
