### ISSUE TITLE
Dropbox-Uploader overloading CPU?

### ISSUE THREAD

**Issue by macosxservice** [andreafabrizi/Dropbox-Uploader#214]
Hello,
I've created a daemonized, bash script that uses Dropbox-Uploader to upload files at scheduled times.  I'm finding that at certain times the activity monitor on my mac shows that "bash" is taking up too much CPU. 

By using  ps -p PID (whatever PID is stated in the Activity Monitor with the high CPU), the terminal outputs "bash /usr/local/bin/dropbox_uploader.sh upload "path to what it's trying to upload"". The size of the file is 40-60kb.  I have to force quit the process.  Any ideas why this may be happening?

Also, can two instances of dropbox_uploader.sh run at the same time, or would this also cause an error/ stall / high CPU?

I should note that when I use dropbox_uploader.sh to upload similar files, not using the LaunchDaemon, it works perfect!

Thanks for a great .sh!

**Comment by andreafabrizi** [comment]
@macosxservice, so the problem happens only using LauchDaemon? 

Yes is possible to run multiple instances of the script at the same time.
