### ISSUE TITLE
function 'urlencode' is incompatible version 2.05b.0

### ISSUE THREAD

**Issue by askrauthein** [andreafabrizi/Dropbox-Uploader#218]
I tried to run dropbox-uploader.sh in a embedded system running Bash 2.05b showing an error (commmand not found) while concatenating string content in function "urlencode" :
    encoded+="${o}"
I was able to correct that changing to:
    encoded="${encoded}${o}"

**Comment by andreafabrizi** [comment]
Hello @askrauthein, thanks for the information, I will fix it in the next release.
