### ISSUE TITLE
feature add suggest

### ISSUE THREAD

**Issue by man9565** [andreafabrizi/Dropbox-Uploader#220]
linux 

find ./ -mmin +10 -print -exec rm -rf {} \;

I'm using Dropbox for backup.

Would it be possible in the drop box Uploading Linux commands like above?
If not you please add the above features?

**Comment by pltuan** [comment]
You can be upload file into Dropbox and after upload success may be delete it into script.

**Comment by andreafabrizi** [comment]
@man9565, you should add this kind of logic in a wrapper script around Dropbox Uploader.
