### ISSUE TITLE
Use the asterisks with the "download" function

### ISSUE THREAD

**Issue by Fenshu** [andreafabrizi/Dropbox-Uploader#221]
Hi Andrea, hi all!
To upload many file from local to remote dropbox directory we can to use the asterisk in UPLOAD function. For example:
```
$ dropbox_uploader.sh -s upload /home/luca/Test_Upload/*.* /Public/Destinazione
```
I could not to use the same option (asterisk) with the **DOWNLOAD** function:
```
$ dropbox_uploader.sh -s download Public/Sorgente/*.* /home/luca/Test_Upload/
 > No such file or directory: /Public/Sorgente/*.*
```
Likely the asterisk are interpreted only in to linux box...
Can something be done about this?

**Comment by idreamsi** [comment]
Hi
I have the same problem, I can not download any file with DOWNLOAD function. After use the download function the following message will be displayed :
> No such file or directory:

**Comment by ABeltramo** [comment]
To download a folder I simply put the folder path like:
```
$ dropbox_uploader.sh -s download Public/Sorgente/
```
Without the asterisks.

**Comment by Fenshu** [comment]
@ABeltramo , likely you did not read well the message ;)
The problem is to download all the files within a folder, not the folder itself

Ciao e grazie!
Luca

**Comment by andreafabrizi** [comment]
@Fenshu, the wildcard is not currently supported by the Dropbox API, so actually is only possible to download a single file or a full folder.
