### ISSUE TITLE
 Please, check your App key and secret...

### ISSUE THREAD

**Issue by darklove2501** [andreafabrizi/Dropbox-Uploader#222]
App key is ************* , App secret is ************** and Access level is Full Dropbox. Looks ok? [y/n]: y

 > Token request... grep: /tmp/du_resp_2502: No such file or directory
sed: can't read /tmp/du_resp_2502: No such file or directory
sed: can't read /tmp/du_resp_2502: No such file or directory
 FAILED

 Please, check your App key and secret...

I'm sure that my app key and app secret is not wrong.

**Comment by andreafabrizi** [comment]
Please check if the /tmp directory exists or not.

**Comment by pltuan** [comment]
Recheck create symbolink into /usr/lib of curl.

**Comment by andreafabrizi** [comment]
Can I consider this issue as solved?

**Comment by Najihel** [comment]
Hi,

I have the same problem : 

```
> App key is XXXX, App secret is XXXX and Access level is App Folder. Looks ok? [y/n]: y

> Token request... grep: /tmp/du_resp_24575: No such file or directory
sed: /tmp/du_resp_24575: No such file or directory
sed: /tmp/du_resp_24575: No such file or directory
FAILED

Please, check your App key and secret...
```

```
-bash-4.1# which curl
/usr/bin/curl
```

```
-bash-4.1# ls -hali /usr/lib/curl
   1055 lrwxrwxrwx    1 root     root          13 Jul 25 20:55 /usr/lib/curl -> /usr/bin/curl
```
