### ISSUE TITLE
Create Crobtab for Automate Upload 

### ISSUE THREAD

**Issue by beykansen** [andreafabrizi/Dropbox-Uploader#223]
Hello. I wrote crontab command execute backup my database files to dropbox. 

SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root
HOME=/

9 2 * * * root /bin/dropbox_uploader.sh upload /home/backup/*.sql / > /var/log/autoback.txt 2>&1

After crontab command executed, Autoback.txt logs shows output like first time dropbox_uploader.sh run script. Actually, I can run dropbox_uploader.sh via manually and linked with my dropbox. (checked /bin/dropbox_uploader.sh info, all is ok) Why crontab doesn't see my dropbox-uploader config ?

**Comment by beykansen** [comment]
Log output : 

This is the first time you run this script.

 1) Open the following URL in your Browser, and log in using your account: https://www.dropbox.com/developers/apps
 2) Click on "Create App", then select "Dropbox API app"
 3) Now go on with the configuration, choosing the app permissions and access restrictions to your DropBox folder
 4) Enter the "App Name" that you prefer (e.g. MyUploader20575175824522)

 Now, click on the "Create App" button.

 When your new App is successfully created, please type the
 App Key, App Secret and the Permission type shown in the confirmation page:

**Comment by andreafabrizi** [comment]
Please read the README first.
