### ISSUE TITLE
Uploads Auto Creating Share Link

### ISSUE THREAD

**Issue by beykansen** [andreafabrizi/Dropbox-Uploader#224]
Hello. After executed dropbox uploader, I can see my files uploaded to dropbox. But share link is active in default. I can also see my new files links tab in dropbox. How can I disable share link as default uploading ? I am using this script in my crontab : https://github.com/andreafabrizi/Dropbox-Uploader/wiki/Simple-backup-script

**Comment by andreafabrizi** [comment]
Hello,
the share link shouldn't be active by default. Do you mean that for every file that you upload you see an entry in the "link" page of the dropbox website?
