### ISSUE TITLE
Can't find files

### ISSUE THREAD

**Issue by lbarberiscanoni** [andreafabrizi/Dropbox-Uploader#228]
Hey, thank you so much for making this because it's pretty great..except it's not working at all on my Mac XD

Whenever I run `sh Dropbox-Uploader/dropbox_uploader.sh upload example.txt Apps/cli-pusher/`
I get `No such file or directory: -e example.txt` as a response

Even if a try to make a directory I get `Creating Directory "-e /path/to/directory/`

It's failing every time despite the fact that download went smoothly and Dropbox had no problem downloading the app. 

Thank you for your help,

Lorenzo

**Comment by pltuan** [comment]
I think you need create file or copy file example.txt into directory Dropbox-Uploader. The directory contain dropbox_uploader.sh or you using full link to example.txt

Example:
sh Dropbox-Uploader/dropbox_uploader.sh upload /test/example.txt Apps/cli-pusher/

**Comment by lbarberiscanoni** [comment]
I just tried both (putting example.txt into the Dropbox-Uploader directory as well as making a wholly separate directory containing example.txt) and the issue persists

**Comment by pltuan** [comment]
You can try
sh Dropbox-Uploader/dropbox_uploader.sh upload /test/example.txt /Apps/cli-pusher/

**Comment by andreafabrizi** [comment]
@lbarberiscanoni, please can you try to run the script in debug mode, while executing the same commands, and send me the output? Thanks.

**Comment by pwojciechowski** [comment]
@andreafabrizi I am having the same issue. If you want some diagnostic info let me know.

**Comment by lbarberiscanoni** [comment]
Ok so I just ran `sh Lorenzo/Github/Dropbox-Uploader/dropbox_uploader.sh -d upload "test.py" /Apps/cli-pusher` and the output was:

0.16
+ RESPONSE_FILE=/tmp/du_resp_debug
+ [[ '' == '' ]]
+ BIN_DEPS='sed basename date grep stat dd mkdir curl'
+ CURL_BIN=curl
+ which sed basename date grep stat dd mkdir curl
+ [[ 0 != 0 ]]
+ which readlink
+ [[ 0 == 0 ]]
++ readlink -m //test
+ [[ '' == \/\t\e\s\t ]]
+ HAVE_READLINK=0
+ builtin printf ''
+ [[ 0 == 0 ]]
+ PRINTF='builtin printf'
+ PRINTF_OPT='-v o'
+ [[ -e /Users/lbarberiscanoni/.dropbox_uploader ]]
+ source /Users/lbarberiscanoni/.dropbox_uploader
+ [[ 0vb8u0kerujb1zs == '' ]]
+ [[ sq6mompyjyj73hb == '' ]]
+ [[ d787pwz5nc1bstf == '' ]]
+ [[ xwgwhhwdy678yc4d == '' ]]
+ [[ dropbox == '' ]]
+ COMMAND=upload
+ ARG1=test.py
+ ARG2=/Apps/cli-pusher
+ let argnum=4-2
+ case $COMMAND in
+ [[ 2 -lt 2 ]]
+ FILE_DST=/Apps/cli-pusher
+ (( i=2+1 ))
+ (( i<4 ))
+ FILE_SRC=test.py
+ db_upload test.py //Apps/cli-pusher
++ normalize_path test.py
+++ echo -e test.py
++ path='-e test.py'
++ [[ 0 == 1 ]]
++ echo '-e test.py'
+ local 'SRC=-e test.py'
++ normalize_path //Apps/cli-pusher
+++ echo -e /Apps/cli-pusher
++ path='-e /Apps/cli-pusher'
++ [[ 0 == 1 ]]
++ echo '-e /Apps/cli-pusher'
+ local 'DST=-e /Apps/cli-pusher'
+ [[ ! -e -e test.py ]]
+ [[ ! -d -e test.py ]]
+ print ' > No such file or directory: -e test.py\n'
+ [[ 0 == 0 ]]
+ echo -ne ' > No such file or directory: -e test.py\n'
-ne  > No such file or directory: -e test.py

+ ERROR_STATUS=1
+ return
+ (( i++  ))
+ (( i<4 ))
+ remove_temp_files
+ [[ 1 == 0 ]]
+ exit 1

**Comment by andreafabrizi** [comment]
Please try the last commit!

**Comment by lbarberiscanoni** [comment]
It just worked! Thank you so much
