### ISSUE TITLE
Problems running in incrond

### ISSUE THREAD

**Issue by eepohboy** [andreafabrizi/Dropbox-Uploader#232]
I have been trying to use Dropbox-Uploader with incrond to automatically upload files copied/moved into a monitored folder. I can run the script from the command line, but not via incrond. Below is a summary of what I have done and tested:

- I am using Raspbian:
Linux myPi 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux

- I have installed according to instructions.

- I have successfully tested uploading using the command line.

- I have copied the .dropbox_uploader to /root/ to allow the script to be ran by root when invoked by incrond

- I have added an entry into incrondtab to monitor new files in a folder:
/home/pi/PhotoBoothProject/forFB IN_CREATE,IN_MOVED_TO /home/pi/Dropbox-Uploader/dropbox_uploader.sh upload $@/$# /forFB/$# 2>&1 >> /tmp/photoBooth.log

According to syslog entry, Incrond is evoked when I move/copy a file into the monitored folder:
Aug 26 01:50:53 myPi incrond[1991]: (root) CMD (/home/pi/Dropbox-Uploader/dropbox_uploader.sh upload /home/pi/PhotoBoothProject/forFB/IMG_2152.JPG /forFB/IMG_2152.JPG 2>&1 >> /tmp/photoBooth.log)

New file in monitored folder is not uploaded and there are not entries in any log files, including /tmp/du_resp_debug when I set DEBUG=1 nothing happens, even though syslog reports the script being executed.

Any advise on how to get the script to run will be appreciated.

Rizal.

ps. I am facing the same problem when I try to invoke the script using python. The python script also being triggered by incrond:

from subprocess import call 
uploadImagetoDropbox = '/home/pi/Dropbox-Uploader/dropbox_uploader.sh upload ' + uploadFolder + '/' + inputFile + ' ' + dropboxFolder + '/' + inputFile
logFile.write(uploadImagetoDropbox + '\n')
call ([uploadImagetoDropbox], shell=True)

Everything else seems to work, except nothing happens when the call() function is executed.

**Comment by andreafabrizi** [comment]
@eepohboy, did you read the paragraph "Running as cron job" on the README file?

**Comment by eepohboy** [comment]
@andreafabrizi yes I did. I just re-tried doing what is suggested and it seems to work now. 

The first time I did it, I used the same AppKey and Secret Key for both users (pi & root).

What I did differently this time was to create a 2nd app in Dropbox and use the new App and Secret key that was generated for the root user. 

The dropbox_uploader script invoked by incrond is now working.

Thanks.
