### ISSUE TITLE
Uploading FAILED

### ISSUE THREAD

**Issue by adiiik** [andreafabrizi/Dropbox-Uploader#234]
I configured the script to work with my Dropbox account, but when on the Dropbox is over a dozen files, the script had problem with sending files. 
When I use the -s parameter, a new unique files are ignored.
If you do not use the -s parameter, the error occurs.

A sample log, at the beginning, the application's folder was empty:

 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-15-39-07-PIREvent.avi" to "/2015-08-30-15-39-07-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-15-39-25-PIREvent.avi" to "/2015-08-30-15-39-25-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-15-47-32-PIREvent.avi" to "/2015-08-30-15-47-32-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-15-47-53-PIREvent.avi" to "/2015-08-30-15-47-53-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-15-49-52-PIREvent.avi" to "/2015-08-30-15-49-52-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-15-50-02-PIREvent.avi" to "/2015-08-30-15-50-02-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-15-50-13-PIREvent.avi" to "/2015-08-30-15-50-13-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-15-51-08-PIREvent.avi" to "/2015-08-30-15-51-08-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-15-54-22-PIREvent.avi" to "/2015-08-30-15-54-22-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-16-17-15-PIREvent.avi" to "/2015-08-30-16-17-15-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-16-18-20-PIREvent.avi" to "/2015-08-30-16-18-20-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-16-18-31-PIREvent.avi" to "/2015-08-30-16-18-31-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-16-18-52-PIREvent.avi" to "/2015-08-30-16-18-52-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-16-19-02-PIREvent.avi" to "/2015-08-30-16-19-02-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-16-19-13-PIREvent.avi" to "/2015-08-30-16-19-13-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-16-19-24-PIREvent.avi" to "/2015-08-30-16-19-24-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-16-19-34-PIREvent.avi" to "/2015-08-30-16-19-34-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-16-33-06-PIREvent.avi" to "/2015-08-30-16-33-06-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-16-33-17-PIREvent.avi" to "/2015-08-30-16-33-17-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-16-33-40-PIREvent.avi" to "/2015-08-30-16-33-40-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-16-33-50-PIREvent.avi" to "/2015-08-30-16-33-50-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-16-51-27-PIREvent.avi" to "/2015-08-30-16-51-27-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-16-51-38-PIREvent.avi" to "/2015-08-30-16-51-38-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-04-13-PIREvent.avi" to "/2015-08-30-17-04-13-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-04-23-PIREvent.avi" to "/2015-08-30-17-04-23-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-04-34-PIREvent.avi" to "/2015-08-30-17-04-34-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-04-45-PIREvent.avi" to "/2015-08-30-17-04-45-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-04-56-PIREvent.avi" to "/2015-08-30-17-04-56-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-07-27-PIREvent.avi" to "/2015-08-30-17-07-27-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-08-42-PIREvent.avi" to "/2015-08-30-17-08-42-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-09-31-PIREvent.avi" to "/2015-08-30-17-09-31-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-09-41-PIREvent.avi" to "/2015-08-30-17-09-41-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-09-52-PIREvent.avi" to "/2015-08-30-17-09-52-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-10-02-PIREvent.avi" to "/2015-08-30-17-10-02-PIREvent.avi"... DONE
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-11-50-PIREvent.avi" to "/"... FAILED
An error occurred requesting /upload
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-12-24-PIREvent.avi" to "/"... FAILED
An error occurred requesting /upload
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-12-35-PIREvent.avi" to "/"... FAILED
An error occurred requesting /upload
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-12-45-PIREvent.avi" to "/"... FAILED
An error occurred requesting /upload
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-13-14-PIREvent.avi" to "/"... FAILED
An error occurred requesting /upload
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-13-43-PIREvent.avi" to "/"... FAILED
An error occurred requesting /upload
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-13-53-PIREvent.avi" to "/"... FAILED
An error occurred requesting /upload
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-14-04-PIREvent.avi" to "/"... FAILED
An error occurred requesting /upload
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-14-14-PIREvent.avi" to "/"... FAILED
An error occurred requesting /upload
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-14-51-PIREvent.avi" to "/"... FAILED
An error occurred requesting /upload
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-16-39-PIREvent.avi" to "/"... FAILED
An error occurred requesting /upload
 > Uploading "/tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201508291202/2015-08-30-17-16-49-PIREvent.avi" to "/"... FAILED
An error occurred requesting /upload

Only when I cleared the application folder on Dropbox, files with the status "failed" can be sent.

**Comment by andreafabrizi** [comment]
@adiiik, could you please send me the full output in debug mode and the content of the du_resp_debug file? Thanks.

**Comment by adiiik** [comment]
Is it secure to provide here debug log? I see that in debug file are shown key and token.

Here is a piece of the log:

+++ date +%s
++ echo 1441104972
+ curl -k -s -i --globoff -o /tmp/du_resp_debug --upload-file /tmp/usb_mount/987A-3F5B/kamera/ImageEvent_201509010647/2015-09-01-12-37-50-PIREvent.avi 'https://api-content.dropbox.com/1/files_put/sandbox/%2f?oauth_consumer_key=-deleted-&oauth_token=-deleted-&oauth_signature_method=PLAINTEXT&oauth_signature=-deleted-&oauth_timestamp=1441104972&oauth_nonce=26209'
+ check_http_response
+ CODE=0
+ case $CODE in
+ grep -q 'HTTP/1.1 400' /tmp/du_resp_debug
++ sed -n -e 's/{"error": "\([^"]*\)"}/\1/p' /tmp/du_resp_debug
+ ERROR_MSG=
+ case $ERROR_MSG in
+ grep -q '^HTTP/1.1 200 OK' /tmp/du_resp_debug
+ print 'FAILED\n'
+ [[ 0 == 0 ]]
+ echo -ne 'FAILED\n'
+ print 'An error occurred requesting /upload\n'
+ [[ 0 == 0 ]]
+ echo -ne 'An error occurred requesting /upload\n'
+ ERROR_STATUS=1
+ (( i++  ))
+ (( i<5 ))
+ remove_temp_files
+ [[ 1 == 0 ]]
+ exit 1

**Comment by andreafabrizi** [comment]
Actually in the du_resp_debug there's only the server response, but if you see confidential informations please remove it.
