### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by mkolchin** [andreafabrizi/Dropbox-Uploader#235]

**Comment by andreafabrizi** [comment]
?

**Comment by mkolchin** [comment]
Bump up - my repo ) plz

**Comment by mkolchin** [comment]
manteiner)

**Comment by mkolchin** [comment]
16.1

**Comment by andreafabrizi** [comment]
I will do it soon

**Comment by mkolchin** [comment]
Thank you.

**Comment by mkolchin** [comment]
Please.We need a working version.

**Comment by andreafabrizi** [comment]
Clone the repo and get the last code, I don't understand what's your proo.

**Comment by mkolchin** [comment]
Do not pick up. Read it will be removed from the repository junk.
