### ISSUE TITLE
download directory contents. not the whole directory

### ISSUE THREAD

**Issue by aristosv** [andreafabrizi/Dropbox-Uploader#236]
/mnt/home/config/dropbox_uploader.sh -s download /latest/music/ /mnt/home/media/

This downloads the folder "music" inside the folder "media"
I want to download the contents of the folder "music" inside the folder "media"

I've tried 
/latest/music/*.mp3
/latest/music/*
/latest/music/*.*

But I get a "No such file or directory" message.

**Comment by andreafabrizi** [comment]
It's not possible to download just the content.
