### ISSUE TITLE
 "Error: Couldn't connect to host." with 500MB+ uploads

### ISSUE THREAD

**Issue by averissimo** [andreafabrizi/Dropbox-Uploader#240]
Getting this error:

"Error: Couldn't connect to host."

Using version 0.16 from github ( revision: 2c6a169 )

curl version: 7.38.0  (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3

Debug information: http://pastebin.com/0ZbNNh7x

    $ cat /tmp/du_resp_debug

    HTTP/1.1 100 Continue

    HTTP/1.1 200 OK
    Server: nginx
    Date: Tue, 15 Sep 2015 13:43:00 GMT
    Content-Type: text/javascript
    Transfer-Encoding: chunked
    Connection: keep-alive
    x-server-response-time: 1430
    x-dropbox-request-id: <hidden>
    pragma: no-cache
    cache-control: no-cache
    X-Robots-Tag: noindex, nofollow, noimageindex
    
    {"expires": "Thu, 17 Sep 2015 13:37:11 +0000", "upload_id": "<hidden>", "offset": 364904448}

Dropbox info:

    Quota:	8960 Mb
    Used:	2835 Mb
    Free:	6124 Mb

**Comment by andreafabrizi** [comment]
@averissimo, the last curl connection returns 7 (Failed to connect to host).
The problem is not related to dropbox uploader, most probably is a network problem.

**Comment by averissimo** [comment]
I've seen in previous issues that dropbox_uploader can retry the upload. __Is there this option on the current version?__

I've tried with "master" and adding -r to the curl command to avoid a fatal error.

**Comment by andreafabrizi** [comment]
@averissimo, please try the last commit. I've fixed a bug that prevents the request to be retried in case of connection failure.

**Comment by averissimo** [comment]
It worked!!

I could not detect if curl failed at some point but I'll monitor in the next few days if it fails again.

Anyway, since yesterday it was failing all uploads and with this new commit it worked again.

Thanks for the help!

ps. this is a fantastic tool for use in servers and even on raspberry pi :)

**Comment by andreafabrizi** [comment]
Thanks! :)

**Comment by filipewalk** [comment]
I got the same error at Version 1.0.

For 3 days, the programed upload stops with this error, in nearby times.
Is there any limit of size, or something else?
