### ISSUE TITLE
Dropbox API sends 400

### ISSUE THREAD

**Issue by nitricware** [andreafabrizi/Dropbox-Uploader#247]
Hy!

The dropbox API sends an Error 400 (Bad Request). This happens on my raspberry pi with the script, the curl command (which I got by calling your script with the -d parameter) isolated and with lynx (where I entered the url form the curl command). It only happens with a directory with an Umlaut (ä) in the Name. Other directories work find. It also works fine on another machine. If I enter the URL in Safari for iOS, the API returns what it should, if I enter it on my MacBook, it works fine. All three devices are in different networks.

Here's what curl saves 

```
HTTP/1.1 400 Bad requestServer: nginxDate: Sun, 18 Oct 2015 10:33:31 GMTContent-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache
X-Dropbox-Request-Id: 8891ce533be5d1ab494912030de308e4

<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
```

Do I really think its a problem with your script? No, not really. But someone on the raspberry pi board does. Maybe he's right. https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=123563&p=830688#p830688

- Kurt

**Comment by andreafabrizi** [comment]
@nitricware, thanks for your report. I agree with you that for sure is not a problem related to the script but most probably to curl. Anyway I will investigate it.

Thanks

**Comment by nitricware** [comment]
Does lynx also use curl? If yes - that could be the problem.

**Comment by andreafabrizi** [comment]
Hello, could you please try with the last version?

**Comment by n1wko** [comment]
I'm getting this error on the first run of the dropbox_uploader script
On the step after cut/pasting the app key and app secret keys, follow the linnk  https://www.dropbox.com/oauth2/authorize?client_id=&token_access_type=offline&response_type=code
returns the html error 400, with detail information Invalid client_id: "".

uname -a:
Linux front.localdomain 5.9.16-200.fc33.x86_64 #1 SMP Mon Dec 21 14:08:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
