### ISSUE TITLE
move local file/directory+subdirs to dropbox

### ISSUE THREAD

**Issue by mferlitsch** [andreafabrizi/Dropbox-Uploader#248]
If the upload is interrupted and I start the script again it always overwrite the files which are already copied to the dropbox.

If a copied file would be deleted from local disk after it is copied sucessfully it would be a nice feature. :-)

**Comment by step21** [comment]
If a file is finished, the file is normally skipped. If the file was only partially uploaded, from what I understand it has to upload again.
If a file should be deleted locally after a successful transfer depends very much on the user/use case. You could easily write your own script (or make pull request for this one) that deletes after a successful transfer.
