### ISSUE TITLE
Repository name relavent to basic features provided

### ISSUE THREAD

**Issue by harshjv** [andreafabrizi/Dropbox-Uploader#249]
At first sight, DropboxUploader seems more related to file upload only. But infact, it's providing so many other features.

So, what about a new name to repo?

Like, DropboxCLI?

**Comment by xxxtonixxx** [comment]
Or DropboxBash (or DropBash), DropboxSH. It's made for to use bash, it's so good that its name included the word "bash/sh" to be easier of to find!  :thumbsup:
