### ISSUE TITLE
Not uploading anything

### ISSUE THREAD

**Issue by Ayzazmujeeb** [andreafabrizi/Dropbox-Uploader#254]
I've installed this on my raspberry pi. its downloading from my dropbox but its not uploading anything

I used the following command to upload
./dropbox_uploader.sh upload /home/pi/mmal/m-video/1.avi

its showing all commands whenever i try to upload.

**Comment by andreafabrizi** [comment]
Hello,
please check the README and read the help shown by the script. You will see that you are missing the destination folder as last parameter.
