### ISSUE TITLE
Unexpected behaviour with wildcards and no target specified

### ISSUE THREAD

**Issue by step21** [andreafabrizi/Dropbox-Uploader#255]
Environment: this is on Win7, in this case running inside bash.

```$ ./dropb upload /c/X16*
 > Uploading "/c/X16-32011.exe" to "/c/X16-37741.exe".............................................................................................**............................................................ DONE
 > Uploading "/c/X16-37699.exe" to "/c/X16-37741.exe"................................................................................................. DONE
 > Uploading "/c/X16-37701.exe" to "/c/X16-37741.exe"....................* ```

As you can see, the shell expansion on the files to upload works perfectly, but then always seems to upload to the same file? Is that normal?

**Comment by clockworkgeek** [comment]
I noticed the same but it does make sense.  The instructions say:

> * **upload** &lt;LOCAL_FILE/DIR ...&gt; &lt;REMOTE_FILE/DIR&gt;  

When there is more than one filename given the script has to assume the last is the destination.  If that's a file then all files are uploaded to the same name, which you are seeing.  If a directory then all files are uploaded to that dir with their own name, which is what you need.  If you don't want to use a directory then this will use the root of your dropbox as the destination:

    ./dropb upload /c/X16* /

**Comment by step21** [comment]
Thanks, yeah I guess it makes sense. I even noticed it later, but still wanted to check if this is as it should be.
