### ISSUE TITLE
FAILED

### ISSUE THREAD

**Issue by ildarkhasanshin** [andreafabrizi/Dropbox-Uploader#256]
./dropbox_uploader.sh share ~/Dropbox/test.txt
FAILED
why?

**Comment by andreafabrizi** [comment]
share <REMOTE_FILE>
Get a public share link for the specified file or directory

**Comment by ildarkhasanshin** [comment]
app-keys entered

**Comment by andreafabrizi** [comment]
The problem is that your are passing a local path "~/Dropbox/test.txt", but the command accept remote location (the file should be already on dropbox)
