### ISSUE TITLE
Can't upload to Dropbox

### ISSUE THREAD

**Issue by gstillo** [andreafabrizi/Dropbox-Uploader#259]
Hello,
I have a rather strange issue with dropbox-uploader.

I can perform all actions (list, mkdir, saveurl, etc) but I can´t upload nothing to Dropbox.

- - -- - -- - -- - --  BASIC TESTS - -- - -- - -- - -- - -- -

user@server:/var/repos/Dropbox-Uploader$ ./dropbox_uploader.sh list
 > Listing "/"... DONE

user@server:/var/repos/Dropbox-Uploader$ ./dropbox_uploader.sh mkdir test
 > Creating Directory "/test"... DONE

user@server:/var/repos/Dropbox-Uploader$ ./dropbox_uploader.sh list
 > Listing "/"... DONE
 [D] 0 test

user@server:/var/repos/Dropbox-Uploader$ ./dropbox_uploader.sh upload LICENSE /
 > Uploading "/var/repos/Dropbox-Uploader/LICENSE" to "/LICENSE"...
Error: Couldn't connect to host.

- - -- - -- - -- - --  UPLOAD DEBUGGING ENABLED - -- - --

user@server:/var/repos/Dropbox-Uploader$ ./dropbox_uploader.sh -d upload ./LICENSE /
0.16
Linux server 3.2.0-4-amd64 #1 SMP Debian 3.2.51-1 x86_64 GNU/Linux
Debian GNU/Linux 7 \n \l

+ RESPONSE_FILE=/tmp/du_resp_debug
+ [[ '' == '' ]]
+ BIN_DEPS='sed basename date grep stat dd mkdir curl'
+ CURL_BIN=curl
+ which sed basename date grep stat dd mkdir curl
+ [[ 0 != 0 ]]
+ which readlink
+ [[ 0 == 0 ]]
++ readlink -m //test
+ [[ /test == \/\t\e\s\t ]]
+ HAVE_READLINK=1
+ builtin printf ''
+ [[ 0 == 0 ]]
+ PRINTF='builtin printf'
+ PRINTF_OPT='-v o'
+ [[ -e /home/gstillo/.dropbox_uploader ]]
+ source /home/gstillo/.dropbox_uploader
+ [[ p7k4x7cgvs483wa == '' ]]
+ [[ vh7j5njaboqvqf0 == '' ]]
+ [[ xu9c3ryw5z242eo == '' ]]
+ [[ wm8pqujylc9q6zia == '' ]]
+ [[ sandbox == '' ]]
+ COMMAND=upload
+ ARG1=./LICENSE
+ ARG2=/
+ let argnum=4-2
+ case $COMMAND in
+ [[ 2 -lt 2 ]]
+ FILE_DST=/
+ (( i=2+1 ))
+ (( i<4 ))
+ FILE_SRC=./LICENSE
+ db_upload ./LICENSE //
++ normalize_path ./LICENSE
+++ builtin printf ./LICENSE
++ path=./LICENSE
++ [[ 1 == 1 ]]
+++ readlink -m ./LICENSE
++ new_path=/var/repos/Dropbox-Uploader/LICENSE
++ [[ E == \/ ]]
++ echo /var/repos/Dropbox-Uploader/LICENSE
+ local SRC=/var/repos/Dropbox-Uploader/LICENSE
++ normalize_path //
+++ builtin printf /
++ path=/
++ [[ 1 == 1 ]]
+++ readlink -m /
++ new_path=/
++ [[ / == \/ ]]
++ [[ 1 > 1 ]]
++ echo /
+ local DST=/
+ [[ ! -e /var/repos/Dropbox-Uploader/LICENSE ]]
+ [[ ! -r /var/repos/Dropbox-Uploader/LICENSE ]]
++ db_stat /
+++ normalize_path /
++++ builtin printf /
+++ path=/
+++ [[ 1 == 1 ]]
++++ readlink -m /
+++ new_path=/
+++ [[ / == \/ ]]
+++ [[ 1 > 1 ]]
+++ echo /
++ local FILE=/
+++ urlencode /
++++ builtin printf /
+++ local string=/
+++ local strlen=1
+++ local encoded=
+++ (( pos=0  ))
+++ (( pos<strlen  ))
+++ c=/
+++ case "$c" in
+++ builtin printf -v o %%%02x ''\''/'
+++ encoded=%2f
+++ (( pos++  ))
+++ (( pos<strlen  ))
+++ echo %2f
+++ utime
++++ date +%s
+++ echo 1448977490
++ curl -s --show-error --globoff -i -o /tmp/du_resp_debug 'https://api.dropbox.com/1/metadata/sandbox/%2f?oauth_consumer_key=BLABLA&oauth_token=BLABLA&oauth_signature_method=PLAINTEXT&oauth_signature=BLABLA&oauth_timestamp=BLABLA&oauth_nonce=BLABLA'
++ check_http_response
++ CODE=0
++ case $CODE in
++ grep -q 'HTTP/1.1 400' /tmp/du_resp_debug
++ grep -q '"is_deleted":' /tmp/du_resp_debug
++ local IS_DELETED=false
++ grep -q '^HTTP/1.1 200 OK' /tmp/du_resp_debug
++ [[ 0 == 0 ]]
++ [[ false != \t\r\u\e ]]
+++ sed -n 's/^\(.*\)\"contents":.\[.*/\1/p' /tmp/du_resp_debug
++ local 'IS_DIR={"hash": "6fbdf4abe1d9ed3eec7ca17ab9d882ed", "thumb_exists": false, "bytes": 0, "path": "/", "is_dir": true, "icon": "folder", "root": "app_folder", '
++ [[ {"hash": "6fbdf4abe1d9ed3eec7ca17ab9d882ed", "thumb_exists": false, "bytes": 0, "path": "/", "is_dir": true, "icon": "folder", "root": "app_folder",  != '' ]]
++ echo DIR
+ TYPE=DIR
+ [[ DIR == \F\I\L\E ]]
+ [[ DIR == \E\R\R ]]
+ [[ DIR == \E\R\R ]]
+ [[ DIR == \D\I\R ]]
++ basename /var/repos/Dropbox-Uploader/LICENSE
+ local filename=LICENSE
+ DST=//LICENSE
+ [[ -d /var/repos/Dropbox-Uploader/LICENSE ]]
+ [[ -e /var/repos/Dropbox-Uploader/LICENSE ]]
+ db_upload_file /var/repos/Dropbox-Uploader/LICENSE //LICENSE
++ normalize_path /var/repos/Dropbox-Uploader/LICENSE
+++ builtin printf /var/repos/Dropbox-Uploader/LICENSE
++ path=/var/repos/Dropbox-Uploader/LICENSE
++ [[ 1 == 1 ]]
+++ readlink -m /var/repos/Dropbox-Uploader/LICENSE
++ new_path=/var/repos/Dropbox-Uploader/LICENSE
++ [[ E == \/ ]]
++ echo /var/repos/Dropbox-Uploader/LICENSE
+ local FILE_SRC=/var/repos/Dropbox-Uploader/LICENSE
++ normalize_path //LICENSE
+++ builtin printf /LICENSE
++ path=/LICENSE
++ [[ 1 == 1 ]]
+++ readlink -m /LICENSE
++ new_path=/LICENSE
++ [[ E == \/ ]]
++ echo /LICENSE
+ local FILE_DST=/LICENSE
+ shopt -s nocasematch
++ basename /LICENSE
+ basefile_dst=LICENSE
+ [[ LICENSE == \t\h\u\m\b\s\.\d\b ]]
+ [[ LICENSE == \d\e\s\k\t\o\p\.\i\n\i ]]
+ [[ LICENSE == \.\d\s\_\s\t\o\r\e ]]
+ [[ LICENSE == \i\c\o\n\\\r ]]
+ [[ LICENSE == \.\d\r\o\p\b\o\x ]]
+ [[ LICENSE == \.\d\r\o\p\b\o\x\.\a\t\t\r ]]
+ shopt -u nocasematch
++ file_size /var/repos/Dropbox-Uploader/LICENSE
+++ stat --format=%s /var/repos/Dropbox-Uploader/LICENSE
++ SIZE=35147
++ '[' 0 -eq 0 ']'
++ echo 35147
++ return
+ FILE_SIZE=35147
++ db_stat /LICENSE
+++ normalize_path /LICENSE
++++ builtin printf /LICENSE
+++ path=/LICENSE
+++ [[ 1 == 1 ]]
++++ readlink -m /LICENSE
+++ new_path=/LICENSE
+++ [[ E == \/ ]]
+++ echo /LICENSE
++ local FILE=/LICENSE
+++ urlencode /LICENSE
++++ builtin printf /LICENSE
+++ local string=/LICENSE
+++ local strlen=8
+++ local encoded=
+++ (( pos=0  ))
+++ (( pos<strlen  ))
+++ c=/
+++ case "$c" in
+++ builtin printf -v o %%%02x ''\''/'
+++ encoded=%2f
+++ (( pos++  ))
+++ (( pos<strlen  ))
+++ c=L
+++ case "$c" in
+++ o=L
+++ encoded=%2fL
+++ (( pos++  ))
+++ (( pos<strlen  ))
+++ c=I
+++ case "$c" in
+++ o=I
+++ encoded=%2fLI
+++ (( pos++  ))
+++ (( pos<strlen  ))
+++ c=C
+++ case "$c" in
+++ o=C
+++ encoded=%2fLIC
+++ (( pos++  ))
+++ (( pos<strlen  ))
+++ c=E
+++ case "$c" in
+++ o=E
+++ encoded=%2fLICE
+++ (( pos++  ))
+++ (( pos<strlen  ))
+++ c=N
+++ case "$c" in
+++ o=N
+++ encoded=%2fLICEN
+++ (( pos++  ))
+++ (( pos<strlen  ))
+++ c=S
+++ case "$c" in
+++ o=S
+++ encoded=%2fLICENS
+++ (( pos++  ))
+++ (( pos<strlen  ))
+++ c=E
+++ case "$c" in
+++ o=E
+++ encoded=%2fLICENSE
+++ (( pos++  ))
+++ (( pos<strlen  ))
+++ echo %2fLICENSE
+++ utime
++++ date +%s
+++ echo 1448977490
++ curl -s --show-error --globoff -i -o /tmp/du_resp_debug 'https://api.dropbox.com/1/metadata/sandbox/%2fLICENSE?oauth_consumer_key=BLABLA&oauth_token=BLABLA&oauth_signature_method=PLAINTEXT&oauth_signature=BLABLA&oauth_timestamp=1448977490&oauth_nonce=BLABLA'
++ check_http_response
++ CODE=0
++ case $CODE in
++ grep -q 'HTTP/1.1 400' /tmp/du_resp_debug
++ grep -q '"is_deleted":' /tmp/du_resp_debug
++ local IS_DELETED=false
++ grep -q '^HTTP/1.1 200 OK' /tmp/du_resp_debug
++ [[ 1 == 0 ]]
++ echo ERR
+ TYPE=ERR
+ [[ ERR != \E\R\R ]]
+ [[ 35147 -gt 157286000 ]]
+ db_simple_upload_file /var/repos/Dropbox-Uploader/LICENSE /LICENSE
++ normalize_path /var/repos/Dropbox-Uploader/LICENSE
+++ builtin printf /var/repos/Dropbox-Uploader/LICENSE
++ path=/var/repos/Dropbox-Uploader/LICENSE
++ [[ 1 == 1 ]]
+++ readlink -m /var/repos/Dropbox-Uploader/LICENSE
++ new_path=/var/repos/Dropbox-Uploader/LICENSE
++ [[ E == \/ ]]
++ echo /var/repos/Dropbox-Uploader/LICENSE
+ local FILE_SRC=/var/repos/Dropbox-Uploader/LICENSE
++ normalize_path /LICENSE
+++ builtin printf /LICENSE
++ path=/LICENSE
++ [[ 1 == 1 ]]
+++ readlink -m /LICENSE
++ new_path=/LICENSE
++ [[ E == \/ ]]
++ echo /LICENSE
+ local FILE_DST=/LICENSE
+ [[ 0 == 1 ]]
+ CURL_PARAMETERS=-s
+ LINE_CR=
+ print ' > Uploading "/var/repos/Dropbox-Uploader/LICENSE" to "/LICENSE"... '
+ [[ 0 == 0 ]]
+ echo -ne ' > Uploading "/var/repos/Dropbox-Uploader/LICENSE" to "/LICENSE"... '
 > Uploading "/var/repos/Dropbox-Uploader/LICENSE" to "/LICENSE"... ++ urlencode /LICENSE
+++ builtin printf /LICENSE
++ local string=/LICENSE
++ local strlen=8
++ local encoded=
++ (( pos=0  ))
++ (( pos<strlen  ))
++ c=/
++ case "$c" in
++ builtin printf -v o %%%02x ''\''/'
++ encoded=%2f
++ (( pos++  ))
++ (( pos<strlen  ))
++ c=L
++ case "$c" in
++ o=L
++ encoded=%2fL
++ (( pos++  ))
++ (( pos<strlen  ))
++ c=I
++ case "$c" in
++ o=I
++ encoded=%2fLI
++ (( pos++  ))
++ (( pos<strlen  ))
++ c=C
++ case "$c" in
++ o=C
++ encoded=%2fLIC
++ (( pos++  ))
++ (( pos<strlen  ))
++ c=E
++ case "$c" in
++ o=E
++ encoded=%2fLICE
++ (( pos++  ))
++ (( pos<strlen  ))
++ c=N
++ case "$c" in
++ o=N
++ encoded=%2fLICEN
++ (( pos++  ))
++ (( pos<strlen  ))
++ c=S
++ case "$c" in
++ o=S
++ encoded=%2fLICENS
++ (( pos++  ))
++ (( pos<strlen  ))
++ c=E
++ case "$c" in
++ o=E
++ encoded=%2fLICENSE
++ (( pos++  ))
++ (( pos<strlen  ))
++ echo %2fLICENSE
++ utime
+++ date +%s
++ echo 1448977491
+ curl -s -i --globoff -o /tmp/du_resp_debug --upload-file /var/repos/Dropbox-Uploader/LICENSE 'https://api-content.dropbox.com/1/files_put/sandbox/%2fLICENSE?oauth_consumer_key=BLABLA&oauth_token=BLABLA&oauth_signature_method=PLAINTEXT&oauth_signature=BLABLA&oauth_timestamp=1448977491&oauth_nonce=BLABLA'
+ check_http_response
+ CODE=7
+ case $CODE in
+ print '\nError: Couldn'\''t connect to host.\n'
+ [[ 0 == 0 ]]
+ echo -ne '\nError: Couldn'\''t connect to host.\n'

Error: Couldn't connect to host.
+ remove_temp_files
+ [[ 1 == 0 ]]
+ exit 1

user@server:/var/repos/Dropbox-Uploader$

- - -- - -- - -- - --  /tmp/du_resp_debug CONTENTS- -- - -- - -- - -- - -

user@server:/var/repos/Dropbox-Uploader$ more /tmp/du_resp_debug
HTTP/1.1 404 Not Found
Server: nginx
Date: Tue, 01 Dec 2015 13:44:51 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
X-Dropbox-Request-Id: c269e12079b22678973f55655c14552e

 Any ideas?

 Cheers and thanks for any help,
 g.

**Comment by Dared87** [comment]
It looks like you are able to reach "api.dropbox.com" (mkdir, list) but not "api-content.dropbox.com" (upload). Do you have any firewall/proxy blocking your way?
