### ISSUE TITLE
Wrong filename sometimes when upload

### ISSUE THREAD

**Issue by netoeuler** [andreafabrizi/Dropbox-Uploader#260]
The normal process is:
user@server:/var/repos/Dropbox-Uploader$ ./dropbox_uploader.sh upload localpath/ remotepath/

I my case, I have a localpath with 22 files named 01, 02, 03, ..., 22. When I upload this path the process is gone normally but sometimes upload the file with the name of the directory which it locate.

Output of my case:
> Upload "path/01" to "path/01"... DONE
> Upload "path/02" to "path/02"... DONE
> Upload "path/03" to "path/03"... DONE
> Upload "path/04" to "path/04"... DONE
> Upload "path/05" to "path/"... DONE
> Upload "path/06" to "path/06"... DONE
> Upload "path/07" to "path/07"... DONE
> Upload "path/08" to "path/08"... DONE
> Upload "path/09" to "path/09"... DONE
> Upload "path/10" to "path/10"... DONE
> Upload "path/11" to "path/"... DONE
> Upload "path/12" to "path/12"... DONE
> Upload "path/13" to "path/13"... DONE
> Upload "path/14" to "path/14"... DONE
> Upload "path/15" to "path/15"... DONE
> Upload "path/16" to "path/16"... DONE
> Upload "path/17" to "path/"... DONE
> Upload "path/18" to "path/18"... DONE
> Upload "path/19" to "path/19"... DONE
> Upload "path/20" to "path/20"... DONE
> Upload "path/21" to "path/21"... DONE
> Upload "path/22" to "path/22"... DONE

This happen sometimes. I look but didn't see any pattern for this, but anyway, I'm submitting the issue.

**Comment by blasto333** [comment]
This has happened to me to; but I do this on a cron task and don't have logs. It seems for me sometimes a file in a sub directory gets copied to the root.

**Comment by Dared87** [comment]
This error appears when the dropbox API returns an error while the function db_stat tries to determine if the destination is a file or directory.

```bash
    #Exits...
    grep -q "^HTTP/1.1 200 OK" "$RESPONSE_FILE" #<--- Response is not ok
    if [[ $? == 0 && $IS_DELETED != "true" ]]; then

        local IS_DIR=$(sed -n 's/^\(.*\)\"contents":.\[.*/\1/p' "$RESPONSE_FILE")

        #It's a directory
        if [[ $IS_DIR != "" ]]; then
            echo "DIR"
        #It's a file
        else
            echo "FILE"
        fi

    #Doesn't exists
    else
        echo "ERR" #<--- It returns ERR instead of DIR
    fi
```
[https://github.com/andreafabrizi/Dropbox-Uploader/blob/871ad082d81bf23e336da9746627bc083c35eb8a/dropbox_uploader.sh#L394-L411](url)

It then assumes that the destination is a file which produces this weird behaviour
```bash
    TYPE=$(db_stat "$DST")

    #If DST it's a file, do nothing, it's the default behaviour
    if [[ $TYPE == "FILE" ]]; then
        DST="$DST"

    #if DST doesn't exists and doesn't ends with a /, it will be the destination file name
    elif [[ $TYPE == "ERR" && "${DST: -1}" != "/" ]]; then #<--- It goes here
        DST="$DST"

    #if DST doesn't exists and ends with a /, it will be the destination folder
    elif [[ $TYPE == "ERR" && "${DST: -1}" == "/" ]]; then
        local filename=$(basename "$SRC")
        DST="$DST/$filename"

    #If DST it'a directory, it will be the destination folder
    elif [[ $TYPE == "DIR" ]]; then #<--- But should go here
        local filename=$(basename "$SRC")
        DST="$DST/$filename"
    fi
```
[https://github.com/andreafabrizi/Dropbox-Uploader/blob/871ad082d81bf23e336da9746627bc083c35eb8a/dropbox_uploader.sh#L436-L455](url)


I don't have the contents of the $RESPONSE_FILE right now, but I've written a script to catch it if the error appears the next time, so I can provide a more information in the next few days.

**Comment by blasto333** [comment]
@Dared87 Thank you so much! This would be a great fix!

**Comment by Dared87** [comment]
@blasto333 Since I think this is a connection related issue, it is not really fixable. But if that's the case, I have a good idea for a workaround that might help us.

**Comment by netoeuler** [comment]
Now that you said that, this problem occurred in a time that my internet connection was unstable, since the internet connection was fixed this problem doesn't occurred again.

**Comment by Dared87** [comment]
This is the response we get, when the internet connection is not stable
```
HTTP/1.1 503 Service Unavailable
Server: nginx
Date: Mon, 22 Feb 2016 23:37:38 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache
X-Dropbox-Request-Id: [hidden]

<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```

Errors like this should be caught by the "check_http_response" function to give the user an appropriate error message and prevent files being created in the wrong folder (and wrong file name).

**Comment by andreafabrizi** [comment]
The problem should be fixed with the last version.
