### ISSUE TITLE
Skip upload functionality

### ISSUE THREAD

**Issue by lrybak** [andreafabrizi/Dropbox-Uploader#266]
First of all thanks for sharing your work. Good job!

I found that skip option (-s) only checks whether both local and remote files exists (only by name). If so it just skip upload.
What about situation when local file changed since last upload? Do "skip" option should check if remote file differ from local one and then force upload instead of skip upload?

**Comment by nilsonpena** [comment]
Good question!!!

**Comment by andreafabrizi** [comment]
Not for the moment

**Comment by AmericanY** [comment]
@andreafabrizi I do have the same question, Looking forward to know if you will add parameter for that task. because it's really will short the time.
