### ISSUE TITLE
curl error code 35

### ISSUE THREAD

**Issue by hotmtk** [andreafabrizi/Dropbox-Uploader#267]
Hello!
I am trying to get it work under Tomato Shibi firmware.
I get the following error:

 > Token request... ++ utime
+++ date +%s
++ echo 1452444871
+ /opt/bin/curl -s --show-error --globoff -i -o /tmp/du_resp_debug --data 'oauth_consumer_key=zzzzzzzzzzzz&oauth_signature_method=PLAINTEXT&oauth_signature=yyyyyyyyyyyyyy%26&oauth_timestamp=1452444871&oauth_nonce=10107' https://api.dropbox.com/1/oauth/request_token
+ check_http_response
+ CODE=35
+ case $CODE in
+ grep -q 'HTTP/1.1 400' /tmp/du_resp_debug
grep: /tmp/du_resp_debug: No such file or directory
++ sed -n 's/oauth_token_secret=\([a-z A-Z 0-9]*\).*/\1/p' /tmp/du_resp_debug
sed: /tmp/du_resp_debug: No such file or directory
+ OAUTH_TOKEN_SECRET=
++ sed -n 's/.*oauth_token=\([a-z A-Z 0-9]*\)/\1/p' /tmp/du_resp_debug
sed: /tmp/du_resp_debug: No such file or directory
+ OAUTH_TOKEN=
+ [[ '' != '' ]]
+ echo -ne ' FAILED\n\n Please, check your App key and secret...\n\n'
 FAILED

 Please, check your App key and secret...

+ remove_temp_files
+ [[ 1 == 0 ]]
+ exit 1

Putting only curl command in bash, it gets:

root@unknown:/home/root# /opt/bin/curl -s --show-error --globoff -i -o /tmp/du_resp_debug --data 'oauth_consumer_key=zzzzzzzzzzzzz&oauth_signature_method=PLAINTEXT&oauth_signature=yyyyyyyyyyyyy%26&oauth_timestamp=1452444871&oauth_nonce=10107' https://api.dropbox.com/1/oauth/request_token
curl: (35) error:0D0890A1:asn1 encoding routines:ASN1_verify:unknown message digest algorithm
root@unknown:/home/root#

p.s. zzzzzzzzzzzzz and yyyyyyyyyyyyy are edited by me P-)

What can I do? Error code 35 is not present in dropbox_uploader.sh and debug files are not present in tmp/ folder...

**Comment by andreafabrizi** [comment]
Check if the /tmp exists or try to change the temp folder location in the script source.

**Comment by hotmtk** [comment]
/tmp folder exists
changed also the folder to /opt/tmp and got the same error 35
My machine is a router with Tomato firmware by Shibi. It has SH shell not BASH shell.
I installed BASH shell via IPKG packages, but I think is not 100% compatible with script.
I also read in forum that version 0.9 worked on Tomato...but I cannot find anywhere that old version. Can you send me to hotmtk@yahoo.com ? Thanks

**Comment by andreafabrizi** [comment]
Hello, could you please try with the last version?
