### ISSUE TITLE
download function not working with DropBox folder containing latin letter e withacute: é è à ....

### ISSUE THREAD

**Issue by laiclair** [andreafabrizi/Dropbox-Uploader#269]
Hello,

I'm using Dropbox-updater on jail of a Freenas 9.3 stable version.
unfortunately folers containing letter like é è à are not downloaded by Dropbox-Uploader.
An error is returned saying the folder doesn't exist.
Usage example :
=> dropbox-uploader.sh download .
Folder on the dropbox :
=> "2014 Photo Céline"

I guess issue is reproductable. let me know if you need more informations.
Thanks,
Regards,

**Comment by bugdevil** [comment]
It's the same for me. All is working well until it reaches a folder with a letter like "é".

It acts like the folder doesn't exist. I have a lot of folders with this type of letters, and it makes the script impossible to use.

**Comment by andreafabrizi** [comment]
Could you please try with the last version?

**Comment by bugdevil** [comment]
Hi,

I just tried it and it seems to work fine now ! thank you for the fix !
