### ISSUE TITLE
cannot download files named with : colon from Dropbox

### ISSUE THREAD

**Issue by ctrngk** [andreafabrizi/Dropbox-Uploader#273]
When I touch a file named 
                  screenshot_22:34:56.png 
and upload by Dropbox_Uploader, everything works fine. I can see it existing in the browser. I can click and  download the file from the browser.
However, when using Dropbox_Uploader to download this file,  it reads "Error writing file ... permission denied"

I tried to rename any files with colon(:) in browser , it fails. It seems that dropbox does not support files names with colon(:). But, it is able to download manually, if there is such existing files in the page.

My question is, do I need to rename all screenshots without colon(:) before uploading, or you guys can come up with a idea to bypass this conflict? 
Thank you

**Comment by andreafabrizi** [comment]
I will check, thanks.

**Comment by antonioribeiro** [comment]
You should avoid using colons on files that might at some point be used on a Windows file system, colons are not valid for filenames on DOS nor NTFS. You may upload those to Dropbox, it works for me, but won't be able to read them on Windows.
