### ISSUE TITLE
Python launch not working

### ISSUE THREAD

**Issue by tylerlindstrand** [andreafabrizi/Dropbox-Uploader#275]
I am struggling to try and get this to work. When I run dropbox_uploader.sh info from the command line it works fine. Then I try calling that command from a python script it fails. I am calling it using the call function. Any help would be greatly appreciated. 

`from subprocess import call`
`status=call(["home/pi/Dropbox-Uploader/dropbox_uploader.sh info:],shell=True)`

![image](https://cloud.githubusercontent.com/assets/17163549/12953747/f63f56de-cfd8-11e5-8678-a0f33dcc453b.png)

![image](https://cloud.githubusercontent.com/assets/17163549/12954383/8fd7d756-cfdb-11e5-90fa-376012dfa1f2.png)

**Comment by andreafabrizi** [comment]
@tylerlindstrand, you should run it in debug mode and post the output.

**Comment by tylerlindstrand** [comment]
@andreafabrizi, thanks for the reply. You will have to forgive me, kind of a newbie. How do I run it in debug mode?

**Comment by andreafabrizi** [comment]
Use the -d option.
