### ISSUE TITLE
Documentation issue for command line

### ISSUE THREAD

**Issue by tomwaldnz** [andreafabrizi/Dropbox-Uploader#278]
The documentation states

`/opt/Dropbox-Uploader/dropbox_uploader.sh COMMAND [PARAMETERS]...`

However this command does not work

`/opt/Dropbox-Uploader/dropbox_uploader.sh upload -s /var/backups/ /`

and this one does (note the -s)

`/opt/Dropbox-Uploader/dropbox_uploader.sh -s upload /var/backups/ /`

Suggest the documentation indicate that optional parameters have to come after the script name, but before the command.

**Comment by andreafabrizi** [comment]
Thanks, fixed!
