### ISSUE TITLE
No such file or directory:  Folder with '»' in filename 

### ISSUE THREAD

**Issue by RomeSilvanus** [andreafabrizi/Dropbox-Uploader#280]
The script drops an error when trying to sync a folder with the » character in it's name:
`No such file or directory: /Folder/Folder/Word1 » Word2 » Word3` 
where "Word1 » Word2 » Word3" is one folder.
This is on Ubuntu Server 14.04.  
  
On my local Mac it looks like this:
`/Folder/Folder/Word1 \u00bb Word2 \u00bb Word3`  
  
  
Is there any workaround for this yet, or any plans to fix it?

**Comment by andreafabrizi** [comment]
Could you please try with the last version?

**Comment by RomeSilvanus** [comment]
@andreafabrizi It does actually work now. Great!
