### ISSUE TITLE
Error: Required program could not be found: dd

### ISSUE THREAD

**Issue by nermindadan** [andreafabrizi/Dropbox-Uploader#282]
Hello!

I am trying to get it to work on my reseller account. It works great on VPS, but for some reason it does not work on reseller.

This is the error when run with -d:

Linux  3.12.41-77.ELK6.x86_64 #1 SMP Fri May 1 18:21:30 CDT 2015 x86_64 x86_64 x86_64 GNU/Linux
+ RESPONSE_FILE=/tmp/du_resp_debug
+ [[ '' == '' ]]
+ BIN_DEPS='sed basename date grep stat dd mkdir curl'
+ CURL_BIN=curl
+ which sed basename date grep stat dd mkdir curl
which: no dd in (/usr/local/jdk/bin:/home/fmm/perl5/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/opt/python27/bin:/usr/local/bin:/usr/X11R6/bin:/home/fmm/bin)
+ [[ 1 != 0 ]]
+ for i in '$BIN_DEPS'
+ which sed
+ for i in '$BIN_DEPS'
+ which basename
+ for i in '$BIN_DEPS'
+ which date
+ for i in '$BIN_DEPS'
+ which grep
+ for i in '$BIN_DEPS'
+ which stat
+ for i in '$BIN_DEPS'
+ which dd
which: no dd in (/usr/local/jdk/bin:/home/fmm/perl5/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/opt/python27/bin:/usr/local/bin:/usr/X11R6/bin:/home/fmm/bin)
+ NOT_FOUND='dd '
+ for i in '$BIN_DEPS'
+ which mkdir
+ for i in '$BIN_DEPS'
+ which curl
+ echo -e 'Error: Required program could not be found: dd '
Error: Required program could not be found: dd
+ exit 1

Any help would be appreciated. 

Thanks!

Nermin.

**Comment by andreafabrizi** [comment]
The error is explanatory: you need the "dd" binary
