### ISSUE TITLE
Erroring on First Install when used in bash

### ISSUE THREAD

**Issue by christopher-paul-shaw** [andreafabrizi/Dropbox-Uploader#287]
Running in bash on an Ubuntu 64 bit 15.10 server.
"-e Error: this script requires the BASH shell!" error when run in bash

**Comment by andreafabrizi** [comment]
The error message is explanatory: you don't have bash installed.

**Comment by cpshaw** [comment]
Even though i do have it installed, run other bash scripts daily and was running it inside bash.
