### ISSUE TITLE
Directory is being uploaded as single file named after the directory?

### ISSUE THREAD

**Issue by Obinice** [andreafabrizi/Dropbox-Uploader#290]
In the past, running the script would very occasionally upload the whole folder as a single file named after the folder. Or, it would upload each file from the folder with no extension, just using the name of the folder as the file name. Dropbox would then fill with files called:

- logs
- logs (1)
- logs (2)
- ...etc

This was so rare as to not be a serious issue until about 13 hours ago, when the issue began occurring 100% of the time on both of my raspberry pi units. I have disabled all dropbox crons until this is resolved to stop my dropbox being flooded with these unusable files.

Is this a known issue with a fix expected? I love dropbox-uploader and greatly appreciate the time and effort you put in to making our lives easier. Thanks!

**Comment by Dared87** [comment]
It's pretty much the same reason for another problem I had and I explained it here https://github.com/andreafabrizi/Dropbox-Uploader/issues/260#issuecomment-185643340

Have you tried the most recent commit from Dropbox-Uploader? https://github.com/andreafabrizi/Dropbox-Uploader/pull/288/commits/7cae502cf7879d8a26167bf0dd91feaa5853b7d9

**Comment by blasto333** [comment]
This started happening to me the past 2 nights. I am going to try the master branch tonight and see what happens

**Comment by jendib** [comment]
It definitely fixes the issue. Thanks :)

**Comment by blasto333** [comment]
No issue last night

**Comment by altring** [comment]
Did not help me. Also I see that in my case only first 33 files in folder have uploaded then this error begin to happen.

**Comment by andreafabrizi** [comment]
The problem should be fixed with the last version.
