### ISSUE TITLE
list fails

### ISSUE THREAD

**Issue by tjluoma** [andreafabrizi/Dropbox-Uploader#291]
Dropbox Uploader v0.16

Suddenly `dropbox_uploader.sh list` is failing, although other commands work:

	 dropbox_uploader.sh  list
	 > Listing "/"... FAILED

Here's the output of ` dropbox_uploader.sh -d list`

[dbup-failed.txt](https://github.com/andreafabrizi/Dropbox-Uploader/files/231828/dbup-failed.txt)

but I can do other things, such as 'mkdir'

	  dropbox_uploader.sh mkdir test2
	  > Creating Directory "/test2"... DONE

so it's can interact with my account.

**Comment by aicpp** [comment]
I have same issue last day. Something break/changed at server side?
Debug mode output:
```
1 HTTP/1.1 301 Moved Permanently^M¬
  2 Server: nginx^M¬
  3 Date: Fri, 22 Apr 2016 20:09:34 GMT^M¬
  4 Content-Type: text/html; charset=utf-8^M¬
  5 Content-Length: 267^M¬
  6 Connection: keep-alive^M¬
```

**Comment by aicpp** [comment]
Upd: already fixed [https://github.com/andreafabrizi/Dropbox-Uploader/pull/288](url)
