### ISSUE TITLE
download fails to find file on dropbox

### ISSUE THREAD

**Issue by simulsys** [andreafabrizi/Dropbox-Uploader#292]
Hi,

My upload code works fine with the file turning up in the /Apps directory. However when I try to download a file from Dropbox to my Raspberry Pi using the "download" command in the place of "upload" per the documentation it says "No such file or directory..." when there manifestly is.

Is there anything you can do to help please?

**Comment by bgib** [comment]
Using dropbox_uploader.sh, download and list stopped working last night (4/21/16).  I can still upload, delete, move, mkdir, and info.  I was able to verify all operations using the dropbox.com website browser interface.

**Comment by jaggs6** [comment]
+1

**Comment by andreafabrizi** [comment]
The problem, due to a change in the Dropbox API, has been already fixed. Please update to the latest version.

**Comment by simulsys** [comment]
'Fraid not. I have just installed the latest version from Git, run the
python program to "download", and it cannot find the file or directory,
which both exist. Sorry to bear bad news, but I thought you ought to know.

I am running v0.16
Many thanks for responding,
Andrew

On 26 April 2016 at 09:51, Andrea Fabrizi <notifications@github.com> wrote:

> Closed #292 <https://github.com/andreafabrizi/Dropbox-Uploader/issues/292>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/andreafabrizi/Dropbox-Uploader/issues/292#event-641170815>
>



-- 
Andrew J. Lewis MSc FLS
Simul Systems Ltd
Chelmsford
www.sysenvir.com
44-(0)7710 588318

Member of Chelmsford Innovation Group

**Comment by Paul-Reed** [comment]
Works fine here using current version.
