### ISSUE TITLE
Another breaking change from Dropbox

### ISSUE THREAD

**Issue by dudeinthemirror** [andreafabrizi/Dropbox-Uploader#293]
It looks like they are now returning a short URL when you invoke 
```
./dropbox_uploader share ...
```

something like:

```
https://db.tt/e4lZhI1b
```

Is there a way we can get to the original URL behind the shortened form ?
Thanks

**Comment by Paul-Reed** [comment]
Yes, it's definitely broken. I was using DU to upload nightly archives to Dropbox, but stopped 21/22nd April.  
Hope it can be fixed...

**Comment by Paul-Reed** [comment]
Hang on! this was fixed before we reported it.
@dudeinthemirror download the latest commit and I think you'll find it fixed now.

**Comment by dudeinthemirror** [comment]
@Paul-Reed : This is a different one than #288. So  `dropbox_uploader.sh share ...` now returns a shortened link. So instead of e.g. `https://www.dropbox.com/s/3dzjpykjce8xs/somefile.html?dl=0` you get something like `https://db.tt/e4lZgI1b`
BTW, I have the code to fix this (bash) if anyone is interested.

**Comment by andreafabrizi** [comment]
Actually by default Dropbox and then Dropbox Uploader returns the short link version. I don't have implemented an option to change it so far, but if you don't like short links just find in the code "short_url=true" and replace with "short_url=false".
