### ISSUE TITLE
How can I edit API key ,Token

### ISSUE THREAD

**Issue by chanapong3** [andreafabrizi/Dropbox-Uploader#294]
or start Wizard configulation like a first time again. I want to change API Key,App token,ETC  Because I change Application on dropbox
Thanks
Chanapong Khotabut

**Comment by Paul-Reed** [comment]
Yes, delete the hidden file;
`/home/pi/.dropbox_uploader`
Then run the script again and it will restart the Wizard.

Paul

**Comment by chanapong3** [comment]
I type in terminal like this "./dropbox_uploader.sh"
it does not start like first time.I dont know how to do it.
It show like this 
  


Dropbox Uploader v0.8.2
Usage: /usr/bin/dropbox_uploader.sh [OPTIONS]...

Options:
	-u [USERNAME] (required if not hardcoded)
	-p [PASSWORD]
	-f [FILE/FOLDER] (required)
	-d [REMOTE_FOLDER] (default: /)
	-v Verbose mode

**Comment by chanapong3** [comment]
I fix it
Thank a lot !!!!

**Comment by psyco3000** [comment]
Hello my friend, i have the same problem, how did you solve it?

**Comment by chanapong3** [comment]
Sry friend it was too long ago.
I cant remember anything.


________________________________
