### ISSUE TITLE
Syntax in last commit

### ISSUE THREAD

**Issue by Shaaah** [andreafabrizi/Dropbox-Uploader#295]
First time starting it up on cygwin : 

>$ ./dropbox_uploader.sh
>./dropbox_uploader.sh: line 870: syntax error near unexpected token `('
>./dropbox_uploader.sh: line 870: `        let free_mb=($quota-$used)/1024/1024

There's an error on line 870, you're missing a $

>let free_mb=($quota-$used)/1024/1024
>.................^

**Comment by andreafabrizi** [comment]
The syntax is correct, probably the bash version used is cygwin doesn't like it.

**Comment by Shaaah** [comment]
Well, you used that syntax about 5 times in the 50 lines before 870, so I was lucky to get a quick fix. Others may not. 

Also, I realised yesterday I was not using the cygwin sh by default, but an old [Portable Git](https://git-scm.com/download/) one.

>$sh.exe --version
>GNU bash, version 3.1.0(1)-release (i686-pc-msys)
>Copyright (C) 2005 Free Software Foundation, Inc.

Compare to cygwin : 

>$ sh --version
>GNU bash, version 4.3.42(4)-release (x86_64-unknown-cygwin)
>Copyright (C) 2013 Free Software Foundation, Inc.

That's probably the root of my problem.
