### ISSUE TITLE
Cloud Cam script-no such file or directory

### ISSUE THREAD

**Issue by AndyMAu** [andreafabrizi/Dropbox-Uploader#299]
I am using this script via Tony Dicola's (adafruit.com)Dropbox uploader
Why doesn't the script work?
see paste below
Thanks
pi@raspberrypi:~ $ git clone https://github.com/andreafabrizi/Dropbox-Uploader.git
-bash: git: command not found
pi@raspberrypi:~ $ cd Dropbox-Uploader
-bash: cd: Dropbox-Uploader: No such file or directory
pi@raspberrypi:~ $ chmod a+x dropbox_uploader.sh
chmod: cannot access ‘dropbox_uploader.sh’: No such file or directory
pi@raspberrypi:~ $ sudo cp dropbox_uploader.sh /usr/local/bin/dropbox_uploader

**Comment by ManuCart** [comment]
use this
https://github.com/ManuCart/RaspberryPi#dropbox-uploader
It's working for me on Raspberry Pi

**Comment by andreafabrizi** [comment]
@AndyMAu, probably you need to install git before?
