### ISSUE TITLE
question: Does this .sh copy always all files or only the changed files?

### ISSUE THREAD

**Issue by dmalisani** [andreafabrizi/Dropbox-Uploader#300]
I need put this this .sh in a cron task (backup) but how is too many files in the folder, 
I need to know if this script can be useful for me
if only copy all the files, it will be too slow

**Comment by sys49152** [comment]
@dmalisani you may want to use rsync instead.

**Comment by andreafabrizi** [comment]
With the -s option you can skip the already existing files.
