### ISSUE TITLE
Upgrade to Dropbox API v2

### ISSUE THREAD

**Issue by brianlenz** [andreafabrizi/Dropbox-Uploader#306]
Apologies if this is already being handled somewhere, but the v1 version of Dropbox's API is now officially deprecated and will stop functioning in one year (June 28, 2017):

https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

Here's a migration guide from v1 to v2:

https://blogs.dropbox.com/developers/2016/04/announcing-the-v1-to-v2-migration-guide/

Thanks for the great script!

**Comment by xfechx** [comment]
I am following the dropbox guide, but seems complex and confusing. 

Does dropbox requires this script to be upgraded to use API v2 ?

Any help would be appreciated

**Comment by brianlenz** [comment]
Yes, this script will need to be upgraded to use v2 of the API in order to continue working after June 28, 2017. It should continue to function in its current form (using v1 of the API) until then.

**Comment by xfechx** [comment]
OK.

And once upgraded to use V2, do we have to make any changes to any scripts
that are dependant on dropbox_uploader.sh ?
Do we need to re-authorize again?

**Comment by brianlenz** [comment]
Per the guide:

https://www.dropbox.com/developers/reference/migration-guide#authentication

OAuth 1 tokens will need to be migrated to OAuth 2. This script uses OAuth 1 currently, so that's a change that will need to happen. Or you can just re-authorize via OAuth 2 once the v2 API changes are in place.

I suppose the ultimate answer to your question will depend on the implementation in the script here, so I can't definitively answer what changes may need to be made to external scripts...

**Comment by ruleroller** [comment]
What should I(not a programer)  do? Just wait for this script update and follow the update? Should I do something in https://www.dropbox.com/developers/apps ?

**Comment by jamesinc** [comment]
@ruleroller there's no immediate hurry to switch, for now I would just wait and see if @andreafabrizi or someone else provides a patch. If not, someone will sooner or later. If no one else does, I'll be forced to eventually, but I'm pretty busy so I'll likely wait until the last second :smile:

**Comment by andreafabrizi** [comment]
Don't worry, we have still one year, I will do the necessary changes before the deadline!

**Comment by ruleroller** [comment]
@andreafabrizi @jamesinc OK, I see. Thanks for your replies and your works. 😄

**Comment by klynchk** [comment]
Many thanks - I was getting close to trying to figure this out :smile:

**Comment by rudiedirkx** [comment]
I couldn't help myself and have started at https://github.com/rudiedirkx/Dropbox-Uploader/blob/api2/dropbox_uploader.sh

Diff so far: https://github.com/andreafabrizi/Dropbox-Uploader/compare/master...rudiedirkx:api2 

I'm not nearly as proficient at bash, so it's all happy paths and very little error handling.

It does all I need it to do, so I might let it rest for a while now:

* `list`
* `list-recursive`
* `info`
* `upload` (both single and chunked)

The set-up is completely broken, because v2's auth works differently. All you need is an `access_token` in the config file:

```
OAUTH_ACCESS_TOKEN=AbcAbcAbcAbcAbcAbcAbcAbcAbcAbcAbcAbcAbcAbc
```

The set-up was pretty damn cool though, so that'll definitely have to come back!

**Comment by severach** [comment]
I didn't wait and completed mine already. Existing configs will continue to work until you decide to reauth.
https://github.com/severach/Dropbox-Uploader

**Comment by maurerr** [comment]
@severach
i get following errors when i try to reauth
- Auth code 43 characters A-Z a-z 0-9 BUT also _ - that i could fix myself
-but final failure was > Token request... ./dropbox_uploader.sh: line 349: CFG_APIVER: unbound variable

**Comment by severach** [comment]
All fixed. I enabled issues so we don't need to pollute this thread.

**Comment by rudiedirkx** [comment]
Schweet. It looks like you do know what you're doing =)

**Comment by brianlenz** [comment]
I can confirm the new script worked flawlessly. Thanks much, Andrea!

**Comment by troyblank** [comment]
I can confirm the new script works great thanks for the effort.

I did notice one thing though, the new script does not overwrite the old file with the upload command if there is an old file with the same name. This used to be the case and the documentation says that's the default behavior. 

I now get something like the below with an upload command:
mongo_backup.tar.gz
mongo_backup.tar (1).gz
mongo_backup.tar (2).gz
....

From the documentation it appears the only way to simulate this old behavior is to delete and then upload. This could be a api v2 change, but maybe consider changing documentation or looking into possible bug.

Again thanks for this!

**Comment by troyblank** [comment]
Disregard! It appears to have been recently fixed >< https://github.com/andreafabrizi/Dropbox-Uploader/commit/765ed457cfce686c34f85cd1fd45887f17037c3a
