### ISSUE TITLE
Download of Greek filename files fails

### ISSUE THREAD

**Issue by tsangiotis** [andreafabrizi/Dropbox-Uploader#307]
I want to make a bulk download of my Dropbox folder witch contains a lot of Greek files.

Latin files download just fine but with Greek filenames I get this behaviour:
```
$ sudo /home/odroid/dropbox_uploader.sh download / /media/ntfs/
...
 > Creating local directory "/media/ntfs/TestDir/ELEC"... DONE
 > Downloading "/TestDir/ELEC/Ελληνικό όνομα.doc" to "/media/ntfs/TestDir/ELEC/Ελληνικό όνομα.doc"... FAILED
...
```

When I `ls` the directory I get this:

```
$ ls /media/ntfs/TestDir/ELEC/
???????? ?????.doc
```

when the uploader moves to the next file, the same command returns nothing:
```
$ ls /media/ntfs/TestDir/ELEC/

```

**Comment by andreafabrizi** [comment]
@tsangiotis, could you please try again with the latest version?
