### ISSUE TITLE
Automatically retry/resume after "Error: Couldn't resolve host."

### ISSUE THREAD

**Issue by wlandau** [andreafabrizi/Dropbox-Uploader#309]
I usually get "Error: Couldn't resolve host." when I upload from a cluster in the background, and currently, I have to keep retrying from the beginning until the upload completes normally. It would help to be able to deal with interrupted connections smoothly.

**Comment by andreafabrizi** [comment]
@wlandau, if the file you are uploading is greater than 150MB, the script upload it in chunks, and actually when there's a problem uploading a chunk, it retries 3 times before returning the error. If you what to be more error tolerant, you can just manually increase this value inside the script.
In the contrary when the file is less than 150MB it will be fully uploaded using a single http request, and in this case you can just play with the curl paramenters to increase the retry times.
