### ISSUE TITLE
Unable to move multiple files to a directory

### ISSUE THREAD

**Issue by rsteveyoung** [andreafabrizi/Dropbox-Uploader#311]
I get the " ... FAILED" error when i try to use the move command in order to move multiple files to a destination directory, here's the code i've been using:

`$ ./dropbox_uploader.sh move *.jpg my-images-dir`
`$ ./dropbox_uploader.sh move ./*.jpg /my-images-dir`
`$ ./dropbox_uploader.sh move *.jpg /my-images-dir`

This one functions well (just one image):
`$ ./dropbox_uploader.sh move my-cool-image.jpg /my-images-dir`

However the script functions fantastic when i use it to upload or download my server backups.

**Any comment would be appreciated!**

**Comment by andreafabrizi** [comment]
@rsteveyoung, the wildcard are supported only by the upload command.
