### ISSUE TITLE
Parameter to overwrite existing file on upload?

### ISSUE THREAD

**Issue by vyp** [andreafabrizi/Dropbox-Uploader#312]
In the readme for the `-s` parameter it says:

> Skip already existing files when download/upload. Default: Overwrite

But when I upload a file that already exists, it just renames to `file (1).ext` or `file (2).ext` or so on (assuming original file is named `file.ext`).

Is it possible this is a bug on just on my system somehow? i.e This is not intended behaviour?

If not, what I did is I changed `"mode": "add"` to `"mode": "overwrite"` on lines [540](https://github.com/andreafabrizi/Dropbox-Uploader/blob/856c10a4f3ff4a4c4e0e6447d2c06c5dd697c179/dropbox_uploader.sh#L540) and [616](https://github.com/andreafabrizi/Dropbox-Uploader/blob/856c10a4f3ff4a4c4e0e6447d2c06c5dd697c179/dropbox_uploader.sh#L616) (documented [here](https://www.dropbox.com/developers/documentation/http/documentation#files-upload)), which works. And normal upload when file doesn't exist also works with this too. But a), not sure if that's correct thing to do, and b), even if it is, I assume you don't want this to be default behavior. So I ask if it would be possible to add this as a parameter option somehow?

Use case is to be able to upload a new version of a file ('update' it). As you already know, dropbox keeps some previous versions of files too on such updates.

In any case, thank you so much for this! :+1: :sparkles:

**Comment by ruleroller** [comment]
The default mode is not “Overwrite” mode maybe.

I update to 0.2, default mode and -s mode were the same, tried upload, they always skipped the exist ones to create file(1), file(2), etc.

cc @andreafabrizi

**Comment by andreafabrizi** [comment]
Should be fixed now!

**Comment by vyp** [comment]
Thank you!

**Comment by yceballost** [comment]
I'm having the same issue 🤔
