### ISSUE TITLE
Download files fails returning Error Writing File Permission Denied

### ISSUE THREAD

**Issue by rsteveyoung** [andreafabrizi/Dropbox-Uploader#313]
Uploading files works fine! But when trying downloading files i get the "> Error writing file /srv/users/cooluser/public/file.tar: permission denied".

I am trying to download like this:
$ ./dropbox_uploader.sh download /my_dropbox_directory/my_file.tar .

I have properly set: $ chmod +x dropbox_uploader.sh
Even i have added my user to sudoers file in order to execute: $ sudo dropbox_uploader.sh

Do i need an extra configuration or something ? What am i doing wrong ?

Thanks in advance!
R. Steve.

**Comment by andreafabrizi** [comment]
Could you please run the script in debug mode (-d) and attach the output (remember to remove your auth token)?

**Comment by mfigueroa** [comment]
I had the same error when attempting to download a Dropbox file inside a directory. Creating the exact directory structure in your filesystem fixes the problem. So if your file in Dropbox is MyDir/Backup/backup.tar.gz, do

> mkdir -p MyDir/Backup
> ./dropbox_uploader.sh download MyDir/Backup/backup.tar.gz .

**Comment by hclausd** [comment]
Dear andreafabrizi,
I have the same issue as rsteveyoung: permission denied with a download, despite having all rights granted via chmod a+rwx. 

In my case, I want to download and overwrite a .js-file (called "MagicMirror-QuoteCatalog.js") in the directory "/home/pi/MagicMirror/modules/MagicMirror-QuoteCatalog/".

How can this be solved? It would be great, if you found time for a reply. The log-file ist attached.

Best, Hendrik

[log_dropboxscript_download.txt](https://github.com/andreafabrizi/Dropbox-Uploader/files/9056527/log_dropboxscript_download.txt)
