### ISSUE TITLE
Can not upload bigger than ~10kB files 

### ISSUE THREAD

**Issue by atmole** [andreafabrizi/Dropbox-Uploader#316]
I deployed the script on a Raspberry Pi and an x64 desktop (the OS is Debian Jessie on both), and all of the functions work. I can list and download files from the specified folder, also able to create directories. The only problem I have is that the **upload** only works for very small (~10 kB) text files. When I try to upload bigger text files or images it never completes. Can anyone tell me what is wrong and how can I fix it?

**Comment by andreafabrizi** [comment]
@atmole please run the script in debug mode (-d) and post the output. Remember to remove you auth token.

**Comment by atmole** [comment]
pi@raspberrypi3:~/Dropbox-Uploader $ ./dropbox_uploader.sh -d upload README.md /
0.2
Linux raspberrypi3 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux
Raspbian GNU/Linux 8 \n \l

+ RESPONSE_FILE=/tmp/du_resp_debug
+ [[ '' == '' ]]
+ BIN_DEPS='sed basename date grep stat dd mkdir curl'
+ CURL_BIN=curl
+ which sed basename date grep stat dd mkdir curl
+ [[ 0 != 0 ]]
+ which readlink
+ [[ 0 == 0 ]]
++ readlink -m //test
+ [[ /test == \/\t\e\s\t ]]
+ HAVE_READLINK=1
+ builtin printf ''
+ [[ 0 == 0 ]]
+ PRINTF='builtin printf'
+ PRINTF_OPT='-v o'
+ [[ -e /home/pi/.dropbox_uploader ]]
+ source /home/pi/.dropbox_uploader
+ [[ '' != '' ]]
+ [[ '' != '' ]]
+ [[ ••••token•••• = '' ]]
+ COMMAND=upload
+ ARG1=README.md
+ ARG2=/
+ let argnum=4-2
+ case $COMMAND in
+ [[ 2 -lt 2 ]]
+ FILE_DST=/
+ (( i=2+1 ))
+ (( i<4 ))
+ FILE_SRC=README.md
+ db_upload README.md //
++ normalize_path README.md
+++ builtin printf README.md
++ path=README.md
++ [[ 1 == 1 ]]
+++ readlink -m README.md
++ new_path=/home/pi/Dropbox-Uploader/README.md
++ [[ d == \/ ]]
++ echo /home/pi/Dropbox-Uploader/README.md
+ local SRC=/home/pi/Dropbox-Uploader/README.md
++ normalize_path //
+++ builtin printf /
++ path=/
++ [[ 1 == 1 ]]
+++ readlink -m /
++ new_path=/
++ [[ / == \/ ]]
++ [[ 1 > 1 ]]
++ echo /
+ local DST=/
+ [[ ! -e /home/pi/Dropbox-Uploader/README.md ]]
+ [[ ! -r /home/pi/Dropbox-Uploader/README.md ]]
++ db_stat /
+++ normalize_path /
++++ builtin printf /
+++ path=/
+++ [[ 1 == 1 ]]
++++ readlink -m /
+++ new_path=/
+++ [[ / == \/ ]]
+++ [[ 1 > 1 ]]
+++ echo /
++ local FILE=/
++ curl -X POST -L -s --show-error --globoff -i -o /tmp/du_resp_debug --header 'Authorization: Bearer ••••token••••' --header 'Content-Type: application/json' --data '{"path": "/"}' https://api.dropboxapi.com/2/files/get_metadata
++ check_http_response
++ CODE=0
++ case $CODE in
++ grep -q 'HTTP/1.1 400' /tmp/du_resp_debug
+++ sed -n -e 's/{"error": "\([^"]*\)"}/\1/p' /tmp/du_resp_debug
++ ERROR_MSG=
++ case $ERROR_MSG in
+++ sed -n 's/{".tag": *"*\([^"]*\)"*.*/\1/p' /tmp/du_resp_debug
++ local TYPE=
++ case $TYPE in
++ echo ERR
+ TYPE=ERR
+ [[ ERR == \F\I\L\E ]]
+ [[ ERR == \E\R\R ]]
+ [[ / != \/ ]]
+ [[ ERR == \E\R\R ]]
+ [[ / == \/ ]]
++ basename /home/pi/Dropbox-Uploader/README.md
+ local filename=README.md
+ DST=//README.md
+ [[ -d /home/pi/Dropbox-Uploader/README.md ]]
+ [[ -e /home/pi/Dropbox-Uploader/README.md ]]
+ db_upload_file /home/pi/Dropbox-Uploader/README.md //README.md
++ normalize_path /home/pi/Dropbox-Uploader/README.md
+++ builtin printf /home/pi/Dropbox-Uploader/README.md
++ path=/home/pi/Dropbox-Uploader/README.md
++ [[ 1 == 1 ]]
+++ readlink -m /home/pi/Dropbox-Uploader/README.md
++ new_path=/home/pi/Dropbox-Uploader/README.md
++ [[ d == \/ ]]
++ echo /home/pi/Dropbox-Uploader/README.md
+ local FILE_SRC=/home/pi/Dropbox-Uploader/README.md
++ normalize_path //README.md
+++ builtin printf /README.md
++ path=/README.md
++ [[ 1 == 1 ]]
+++ readlink -m /README.md
++ new_path=/README.md
++ [[ d == \/ ]]
++ echo /README.md
+ local FILE_DST=/README.md
+ shopt -s nocasematch
++ basename /README.md
+ basefile_dst=README.md
+ [[ README.md == \t\h\u\m\b\s\.\d\b ]]
+ [[ README.md == \d\e\s\k\t\o\p\.\i\n\i ]]
+ [[ README.md == \.\d\s\_\s\t\o\r\e ]]
+ [[ README.md == \i\c\o\n\\\r ]]
+ [[ README.md == \.\d\r\o\p\b\o\x ]]
+ [[ README.md == \.\d\r\o\p\b\o\x\.\a\t\t\r ]]
+ shopt -u nocasematch
++ file_size /home/pi/Dropbox-Uploader/README.md
+++ stat --format=%s /home/pi/Dropbox-Uploader/README.md
++ SIZE=7497
++ '[' 0 -eq 0 ']'
++ echo 7497
++ return
+ FILE_SIZE=7497
++ db_stat /README.md
+++ normalize_path /README.md
++++ builtin printf /README.md
+++ path=/README.md
+++ [[ 1 == 1 ]]
++++ readlink -m /README.md
+++ new_path=/README.md
+++ [[ d == \/ ]]
+++ echo /README.md
++ local FILE=/README.md
++ curl -X POST -L -s --show-error --globoff -i -o /tmp/du_resp_debug --header 'Authorization: Bearer ••••token••••' --header 'Content-Type: application/json' --data '{"path": "/README.md"}' https://api.dropboxapi.com/2/files/get_metadata
++ check_http_response
++ CODE=0
++ case $CODE in
++ grep -q 'HTTP/1.1 400' /tmp/du_resp_debug
+++ sed -n 's/{".tag": *"*\([^"]*\)"*.*/\1/p' /tmp/du_resp_debug
++ local 'TYPE={"error_summary": "path/not_found/", "error": path'
++ case $TYPE in
++ echo ERR
+ TYPE=ERR
+ [[ ERR != \E\R\R ]]
+ [[ 7497 -gt 157286000 ]]
+ db_simple_upload_file /home/pi/Dropbox-Uploader/README.md /README.md
++ normalize_path /home/pi/Dropbox-Uploader/README.md
+++ builtin printf /home/pi/Dropbox-Uploader/README.md
++ path=/home/pi/Dropbox-Uploader/README.md
++ [[ 1 == 1 ]]
+++ readlink -m /home/pi/Dropbox-Uploader/README.md
++ new_path=/home/pi/Dropbox-Uploader/README.md
++ [[ d == \/ ]]
++ echo /home/pi/Dropbox-Uploader/README.md
+ local FILE_SRC=/home/pi/Dropbox-Uploader/README.md
++ normalize_path /README.md
+++ builtin printf /README.md
++ path=/README.md
++ [[ 1 == 1 ]]
+++ readlink -m /README.md
++ new_path=/README.md
++ [[ d == \/ ]]
++ echo /README.md
+ local FILE_DST=/README.md
+ [[ 0 == 1 ]]
+ CURL_PARAMETERS='-L -s'
+ LINE_CR=
+ print ' > Uploading "/home/pi/Dropbox-Uploader/README.md" to "/README.md"... '
+ [[ 0 == 0 ]]
+ echo -ne ' > Uploading "/home/pi/Dropbox-Uploader/README.md" to "/README.md"... '
 > Uploading "/home/pi/Dropbox-Uploader/README.md" to "/README.md"... + curl -L -s -X POST -i --globoff -o /tmp/du_resp_debug --header 'Authorization: Bearer ••••token••••' --header 'Dropbox-API-Arg: {"path": "/README.md","mode": "overwrite","autorename": true,"mute": false}' --header 'Content-Type: application/octet-stream' --data-binary @/home/pi/Dropbox-Uploader/README.md https://content.dropboxapi.com/2/files/upload

**Comment by andreafabrizi** [comment]
I tried exactly your command with the same file and it works fine for me.

Please, try to manually run the curl command as following (replace the placeholder with your real token):

`curl -v -L -X POST -i --globoff -o /tmp/du_resp_debug --header 'Authorization: Bearer ***TOKEN***' --header 'Dropbox-API-Arg: {"path": "/README.md","mode": "overwrite","autorename": true,"mute": false}' --header 'Content-Type: application/octet-stream' --data-binary @/home/pi/Dropbox-Uploader/README.md https://content.dropboxapi.com/2/files/upload`

In verbose mode curl should give you an idea why the request is not going on.

**Comment by atmole** [comment]
pi@raspberrypi3:~/Dropbox-Uploader $ curl -v -L -X POST -i --globoff -o /tmp/du_resp_debug --header 'Authorization: Bearer ****TOKEN****' --header 'Dropbox-API-Arg: {"path": "/README.md","mode": "overwrite","autorename": true,"mute": false}' --header 'Content-Type: application/octet-stream' --data-binary @/home/pi/Dropbox-Uploader/README.md https://content.dropboxapi.com/2/files/upload
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 45.58.70.4...
* Connected to content.dropboxapi.com (45.58.70.4) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: OU=Domain Control Validated; CN=dl.dropboxusercontent.com
* 	 start date: 2016-07-09 01:10:38 GMT
* 	 expire date: 2017-05-07 20:27:38 GMT
* 	 subjectAltName: content.dropboxapi.com matched
* 	 issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
* 	 SSL certificate verify ok.
> POST /2/files/upload HTTP/1.1
> User-Agent: curl/7.38.0
> Host: content.dropboxapi.com
> Accept: */*
> Authorization: Bearer ****TOKEN****
> Dropbox-API-Arg: {"path": "/README.md","mode": "overwrite","autorename": true,"mute": false}
> Content-Type: application/octet-stream
> Content-Length: 7497
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
} [data not shown]
100  7497    0     0  100  7497      0    123  0:01:00  0:01:00 --:--:--     0* Empty reply from server
* Connection #0 to host content.dropboxapi.com left intact
curl: (52) Empty reply from server

**Comment by andreafabrizi** [comment]
Curl said "Empty reply from server".
I also tried to connect to the same dropbox server 45.58.70.4 but it works for me. Probably it's a network problem.

**Comment by atmole** [comment]
The weird thing is that the script works on my Mac perfectly and it also worked last year on the Raspberry Pi with a previous version of _Raspbian_ of course. I am suspecting that the latest Debian is messing it up. I could not find any similar complaint on the web however.

**Comment by andreafabrizi** [comment]
You can also try a different cURL version, it could be the cause of the problem as well.

**Comment by Paul-Reed** [comment]
Works fine here - Raspberry Pi 2, latest Debian Jessie.

**Comment by atmole** [comment]
Thanks both for your help. I appreciate it.

**Comment by kidtire** [comment]
I have a similar problem.  I can write files up to 800 bytes but fails at 1000 bytes.  This account was working fine on an older Raspberry Pi 2 with Jessie.  Now running Raspberry Pi 3 B+ with Stretch.
