### ISSUE TITLE
API v1 is now deprecated! Does it affect Dropbox Uploader?

### ISSUE THREAD

**Issue by ahmadawais** [andreafabrizi/Dropbox-Uploader#318]
API v1 is now deprecated! Does it affect Dropbox Uploader?
Kindly refer to the blog post https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

**Comment by andreafabrizi** [comment]
The script has been already upgraded to the API v2.

**Comment by ahmadawais** [comment]
Thanks a lot for letting me know and maintaining this awesome script!
