### ISSUE TITLE
Uploaded files not sync'ed by Dropbox client

### ISSUE THREAD

**Issue by gadget1999** [andreafabrizi/Dropbox-Uploader#320]
Not sure if it's just me. When I use the script to upload files to Dropbox, the files are not sync'ed by Dropbox client. (I can see the files in Dropbox by using web browser). When I use web browser to upload the same file, then the file will be synced' by Dropbox client. Not sure Dropbox client uses some properties to sync?

Environment info:
* upload script used on Raspberry Pi (Raspbian Jessie)
* Dropbox client on Windows 10

**Comment by andreafabrizi** [comment]
Hello, for sure the problem is not linked with the script. If you are sure that it's not a misconfiguration of your dropbox client, probably the Dropbox support can help you.
