### ISSUE TITLE
need clarification on doing a cron job for dropbox uploader

### ISSUE THREAD

**Issue by ameyring** [andreafabrizi/Dropbox-Uploader#322]
Hi,
I've gotten dropbox uploader working at the command line in Raspberry Pi Version 2B. However, when I put it into a cron job, it doesn't work. Here's a snippet of two lines in my .sh file for cron:
raspistill -w 400 -h 300 -o /home/pi/timelapse/$filedate.jpg
dropbox_uploader upload /home/pi/timelapse/$filedate.jpg "upload/"

The raspistill command works fine at command line and in cron, but the same doesn't apply to dropbox_uploader in cron. Can you help? Thanks.

**Comment by slootsky** [comment]
Redirect errors to a log file and see if there are any hints. 

dropbox_uploader upload /home/pi/timelapse/$filedate.jpg "upload/"  2>> /home/pi/dropbox_uploader.log 

Are you sure that the cronjob is running? (is the image file still there?)

**Comment by andreafabrizi** [comment]
@ameyring please check the "Running as cron job" section in the README

**Comment by ameyring** [comment]
Thank you for responding. The log file shows dropbox_unloader as an unknown command. I have no problem running dropbox_unloader from any directory and the cron job is putting pictures in the correct directory. I don't see anything in the README file relevant to me, although I'm not sure I have the -f command in the right spot (I put it before the filename as I've seen in other programs). Thanks again.

**Comment by andreafabrizi** [comment]
Probably because the script is not in your PATH. Try to specify the full path of the script in crontab.

**Comment by ameyring** [comment]
Nothing seemed to work with crontab, no matter what I tried to set up as my directories. It's as if crontab doesn't like programs accessing Dropbox. Managed to create a python program that executes Dropbox-Uploader without crontab and it works great. Use it to record images when a PIR sensor is tripped. Sent a donation for your time. Thanks.

**Comment by chevillet** [comment]
Did you try using the full path to dropbox_uploader in the crontab?
Even if you can run dropbox_uploader from any path yourself, cron often works better with full paths.
