### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by airsoftsoldrecn9** [andreafabrizi/Dropbox-Uploader#324]
I am receiving the following responses when attempting to use the script.

root@HomeServer:/opt/share/dropbox_sync# ./dropbox_uploader.sh info
Dropbox Uploader v0.2

 > Getting info... grep: /tmp/du_resp_15686: No such file or directory
grep: /tmp/du_resp_15686: No such file or directory
FAILED

root@HomeServer:/opt/share/dropbox_sync# ./dropbox_uploader.sh list
 > Listing "/"... grep: /tmp/du_resp_9849: No such file or directory
grep: /tmp/du_resp_9849: No such file or directory
FAILED

root@HomeServer:/opt/share/dropbox_sync# ./dropbox_uploader.sh mkdir test
 > Creating Directory "/test"... grep: /tmp/du_resp_4802: No such file or directory
grep: /tmp/du_resp_4802: No such file or directory
grep: /tmp/du_resp_4802: No such file or directory
FAILED

Further details:

root@HomeServer:/opt/share/dropbox_sync# ./dropbox_uploader.sh -d mkdir test
0.2
Linux HomeServer 2.6.22.19 #7 Tue Nov 30 14:44:12 EST 2010 mips GNU/Linux
+ RESPONSE_FILE=/tmp/du_resp_debug
+ [[ '' == '' ]]
+ BIN_DEPS='sed basename date grep stat dd mkdir curl'
+ CURL_BIN=curl
+ which sed basename date grep stat dd mkdir curl
+ [[ 0 != 0 ]]
+ which readlink
+ [[ 0 == 0 ]]
++ readlink -m //test
+ [[ '' == \/\t\e\s\t ]]
+ HAVE_READLINK=0
+ builtin printf ''
+ [[ 0 == 0 ]]
+ PRINTF='builtin printf'
+ PRINTF_OPT='-v o'
+ [[ -e /root/.dropbox_uploader ]]
+ source /root/.dropbox_uploader
+ [[ '' != '' ]]
+ [[ '' != '' ]]
+ [[ xf0YHq9L8kMAAAAAAAAUejVAKQLftrk7F9TIZfZk_GCoeGS0KJydAiLVT3X-wcBU = '' ]]
+ COMMAND=mkdir
+ ARG1=test
+ ARG2=
+ let argnum=3-2
+ case $COMMAND in
+ [[ 1 -lt 1 ]]
+ DIR_DST=test
+ db_mkdir /test
++ normalize_path /test
+++ builtin printf /test
++ path=/test
++ [[ 0 == 1 ]]
++ echo /test
+ local DIR_DST=/test
+ print ' > Creating Directory "/test"... '
+ [[ 0 == 0 ]]
+ echo -ne ' > Creating Directory "/test"... '
 > Creating Directory "/test"... + curl -X POST -L -s --show-error --globoff -i -o /tmp/du_resp_debug --header 'Authorization: Bearer xf0YHq9L8kMAAAAAAAAUejVAKQLftrk7F9TIZfZk_GCoeGS0KJydAiLVT3X-wcBU' --header 'Content-Type: application/json' --data '{"path": "/test"}' https://api.dropboxapi.com/2/files/create_folder
+ check_http_response
+ CODE=35
+ case $CODE in
+ grep -q 'HTTP/1.1 400' /tmp/du_resp_debug
grep: /tmp/du_resp_debug: No such file or directory
+ grep -q '^HTTP/1.1 200 OK' /tmp/du_resp_debug
grep: /tmp/du_resp_debug: No such file or directory
+ grep -q '^HTTP/1.1 403 Forbidden' /tmp/du_resp_debug
grep: /tmp/du_resp_debug: No such file or directory
+ print 'FAILED\n'
+ [[ 0 == 0 ]]
+ echo -ne 'FAILED\n'
FAILED
+ ERROR_STATUS=1
+ remove_temp_files
+ [[ 1 == 0 ]]
+ exit 1

root@HomeServer:/opt/share/dropbox_sync# ./dropbox_uploader.sh -d list
0.2
Linux HomeServer 2.6.22.19 #7 Tue Nov 30 14:44:12 EST 2010 mips GNU/Linux
+ RESPONSE_FILE=/tmp/du_resp_debug
+ [[ '' == '' ]]
+ BIN_DEPS='sed basename date grep stat dd mkdir curl'
+ CURL_BIN=curl
+ which sed basename date grep stat dd mkdir curl
+ [[ 0 != 0 ]]
+ which readlink
+ [[ 0 == 0 ]]
++ readlink -m //test
+ [[ '' == \/\t\e\s\t ]]
+ HAVE_READLINK=0
+ builtin printf ''
+ [[ 0 == 0 ]]
+ PRINTF='builtin printf'
+ PRINTF_OPT='-v o'
+ [[ -e /root/.dropbox_uploader ]]
+ source /root/.dropbox_uploader
+ [[ '' != '' ]]
+ [[ '' != '' ]]
+ [[ xf0YHq9L8kMAAAAAAAAUejVAKQLftrk7F9TIZfZk_GCoeGS0KJydAiLVT3X-wcBU = '' ]]
+ COMMAND=list
+ ARG1=
+ ARG2=
+ let argnum=2-2
+ case $COMMAND in
+ DIR_DST=
+ [[ '' == '' ]]
+ DIR_DST=/
+ db_list //
++ normalize_path //
+++ builtin printf /
++ path=/
++ [[ 0 == 1 ]]
++ echo /
+ local DIR_DST=/
+ print ' > Listing "/"... '
+ [[ 0 == 0 ]]
+ echo -ne ' > Listing "/"... '
 > Listing "/"... + [[ / == \/ ]]
+ DIR_DST=
+ curl -X POST -L -s --show-error --globoff -i -o /tmp/du_resp_debug --header 'Authorization: Bearer xf0YHq9L8kMAAAAAAAAUejVAKQLftrk7F9TIZfZk_GCoeGS0KJydAiLVT3X-wcBU' --header 'Content-Type: application/json' --data '{"path": "","include_media_info": false,"include_deleted": false,"include_has_explicit_shared_members": false}' https://api.dropboxapi.com/2/files/list_folder
+ check_http_response
+ CODE=35
+ case $CODE in
+ grep -q 'HTTP/1.1 400' /tmp/du_resp_debug
grep: /tmp/du_resp_debug: No such file or directory
+ grep -q '^HTTP/1.1 200 OK' /tmp/du_resp_debug
grep: /tmp/du_resp_debug: No such file or directory
+ print 'FAILED\n'
+ [[ 0 == 0 ]]
+ echo -ne 'FAILED\n'
FAILED
+ ERROR_STATUS=1
+ remove_temp_files
+ [[ 1 == 0 ]]
+ exit 1

**Comment by andreafabrizi** [comment]
@airsoftsoldrecn9 try to change the default tmp folder (line 35 of the script), probably the default /tmp is not writable or doesn't exists.

**Comment by airsoftsoldrecn9** [comment]
Changed suggested line, 35, as well as lines 32 for curl binary location and line 23 for config file location/filename.

<Within dropbox_uploader.sh>
--------------------------------------------
#Default configuration file
CONFIG_FILE=/opt/share/dropbox_sync/dropbox_uploader.conf

#Default chunk size in Mb for the upload process
#It is recommended to increase this value only if you have enough free space on your /t$
#Lower values may increase the number of http requests
CHUNK_SIZE=50

#Curl location
#If not set, curl will be searched into the $PATH
#CURL_BIN="/opt/bin/curl"

#Default values
TMP_DIR="/opt/share/dropbox_sync/tmp"
DEBUG=0
QUIET=0
SHOW_PROGRESSBAR=0
SKIP_EXISTING_FILES=0
ERROR_STATUS=0
-----------------------------------
From ls (ownership and permissions are probably not necessary as specified but figured it could not hurt for testing purposes).

[root@HomeServer dropbox_sync]$ ls -l /opt/share/dropbox_sync/
-rw-r--r--    1 root     root         8348 Sep 17 12:19 CHANGELOG.md
-rw-r--r--    1 root     root            0 Sep 17 22:34 Creating
-rw-r--r--    1 root     root        35147 Sep 17 12:19 LICENSE
-rw-r--r--    1 root     root            0 Sep 19 20:39 Listing
-rw-r--r--    1 root     root         7287 Sep 17 12:19 README.md
-rwxr-xr-x    1 root     root         8681 Sep 17 12:19 dropShell.sh
-rwxr-xr-x    1 root     root           84 Sep 19 20:31 dropbox_uploader.conf
-rwxr-xr-x    1 root     root        41967 Sep 19 20:34 dropbox_uploader.sh
-rwxr-xr-x    1 root     root         2201 Sep 17 12:19 testUnit.sh
drwxrwxrwx    2 root     root         4096 Sep 17 22:02 tmp

NOTE:
Finally figured out that using the insecure option will allow me to properly send the curl command. I have been running into this before just using curl alone where I am receiving "network not reachable" responses.  I do not have ipv6 addressing configured within the iptables on the router (not sure if I can even do that anyway). If anybody runs across problems like this, suggestion would be to try  the insecure option (-k) during debugging.

Additionally I could not use the following due to some sort of write restrictions on my filesystem (odd considering the ownership parameters for the directory). I edited the script as follows in order to work-around the problem. It would appear things will be overwritten between subsequent commands; however, at the moment, I do not see that to be a problem.

RESPONSE_FILE="$TMP_DIR/du_resp_$RANDOM"
CHUNK_FILE="$TMP_DIR/du_chunk_$RANDOM"
TEMP_FILE="$TMP_DIR/du_tmp_$RANDOM"

(RANDOM string is generated from a random seed value, I suppose (did not look for it in the script))

Altered to:

RESPONSE_FILE="$TMP_DIR/du_resp_"
CHUNK_FILE="$TMP_DIR/du_chunk_"
TEMP_FILE="$TMP_DIR/du_tmp_"

**Comment by airsoftsoldrecn9** [comment]
[root@HomeServer dropbox_sync]$ bash ./dropbox_uploader.sh -k list
 > Listing "/"... DONE
 [D]           arduino
 [D]           Camaro stuff
 [D]           Camera Uploads
 [D]           lara
 [D]           ebay
 [D]           grad_project
 [D]           DRUPS_Design
 [D]           business_forms
 [D]           BlackBerry
 [D]           Website_Development
 [D]           Finances
 [D]           House_Sale
 [D]           KM Stuff
 [D]           InsurancePayouts
 [D]           House_Finances
 [D]           dropbox-python-sdk-2.2.0
 [F] 149140679 VID_20160623_191128.mp4
 [F] 1219544   IMG_20160708_192817.jpg
 [F] 1717958   IMG_20160628_185728.jpg
 [F] 1682261   IMG_20160628_185720.jpg
 [F] 1329320   IMG_20160628_185619.jpg
 [F] 1498578   IMG_20160628_185609.jpg
 [F] 1496644   IMG_20160628_185601.jpg
 [F] 1850050   IMG_20160628_185552.jpg
 [F] 3630783   VID_20160628_185540.mp4
 [F] 1962629   IMG_20160628_183915.jpg
 [F] 1823912   IMG_20160628_183846.jpg
[root@HomeServer dropbox_sync]$ bash ./dropbox_uploader.sh -k mkdir test1
 > Creating Directory "/test1"... DONE

**Comment by andreafabrizi** [comment]
Very good! Thanks for having reported how you have solved the problem.
