### ISSUE TITLE
mistake in the Token

### ISSUE THREAD

**Issue by asisrodriguezntdhoy** [andreafabrizi/Dropbox-Uploader#327]
hello,
when instal Dropbox-Uploader i put wrong the Token.
Please, how can I fix it?
thanks
asis

**Comment by Paul-Reed** [comment]
The config (a hidden file) - .dropbox_uploader should be already saved in root. Simple delete it, and run dropbox-uploader again, and it will enter setup once again.

Paul

**Comment by ManuCart** [comment]
Delete the file `.dropbox-uploader`
located in your home folder and run again

**Comment by andreafabrizi** [comment]
./dropbox_uploader.sh unlink
