### ISSUE TITLE
after installing can not see Dropbox-Uploader directory

### ISSUE THREAD

**Issue by asisrodriguezntdhoy** [andreafabrizi/Dropbox-Uploader#328]
hello , i have mount one RPi new with ubuntu MATE and after installing can not see Dropbox-Uploader directory.
i can see it in the console but not in the grafic window :-(
please, any idea to solve it?
thanks
Asis

**Comment by asisrodriguezntdhoy** [comment]
please, help. i have 5 Rpi (trying to synchronize) and Dropbox-Uploader only work in one but in the other 4, I can even download files... but can't access to the folder.
I try using diferent Dropbox-apps but ... nothing...
I don't understand too much of computing so, I'm not able to solve by myself.
thanks in advance.
asis

**Comment by andreafabrizi** [comment]
Sorry but without additional information I can't help you. Give me the output of the command at least.

**Comment by asisrodriguezntdhoy** [comment]
Thanks very much, which is the output command? How can I do it?

Thanks very much.

Asis 

 

De: Andrea Fabrizi [mailto:notifications@github.com] 
Enviado el: lunes, 26 de septiembre de 2016 8:45
Para: andreafabrizi/Dropbox-Uploader <Dropbox-Uploader@noreply.github.com>
CC: asisrodriguezntdhoy <info@ntdhoy.com>; Author <author@noreply.github.com>
Asunto: Re: [andreafabrizi/Dropbox-Uploader] after installing can not see Dropbox-Uploader directory (#328)

 

Sorry but without additional information I can't help you. Give me the output of the command at least.

**Comment by andreafabrizi** [comment]
when you run ./dropbox_uploader.sh upload ....
what the script write on the console

**Comment by asisrodriguezntdhoy** [comment]
Ok thanks, i will send you in a couple of houer (now I’m at the office and I can’t access to my Pi)

Gracie.

Asís Rodríguez, Director de Publicaciones NTDhoy, S.L. >> 16 AÑOS ONLINE >> 915483811 y 626981059 >> info@ntdhoy.com >> Skype (asisrodriguez) 

 

De: Andrea Fabrizi [mailto:notifications@github.com] 
Enviado el: lunes, 26 de septiembre de 2016 9:25
Para: andreafabrizi/Dropbox-Uploader <Dropbox-Uploader@noreply.github.com>
CC: asisrodriguezntdhoy <info@ntdhoy.com>; Author <author@noreply.github.com>
Asunto: Re: [andreafabrizi/Dropbox-Uploader] after installing can not see Dropbox-Uploader directory (#328)

 

when you run ./dropbox_uploader.sh upload ....
what the script write on the console

**Comment by asisrodriguezntdhoy** [comment]
here you have:
root@pi31:~# cd Dropbox-Uploader
root@pi31:~/Dropbox-Uploader# ls
CHANGELOG.md         dropShell.sh  README.md
dropbox_uploader.sh  LICENSE       testUnit.sh
root@pi31:~/Dropbox-Uploader# ./dropbox_uploader.sh download /reiniciar/pi34enlaces.sh
 > Downloading "/reiniciar/pi34enlaces.sh" to "/root/Dropbox-Uploader/pi34enlaces.sh"... DONE
root@pi31:~/Dropbox-Uploader#

but in the graphic window... ther is nosuch folder :-(
THANKS.
Asis

**Comment by asisrodriguezntdhoy** [comment]
please Help this is crazy and I do know how solve it.
I see sometimes you ask for the debug, so her you have perhaps it help to solve:
1.0
Linux pi32 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l armv7l armv7l GNU/Linux
Ubuntu 16.04 LTS \n \l

+ RESPONSE_FILE=/tmp/du_resp_debug
+ [[ '' == '' ]]
+ BIN_DEPS='sed basename date grep stat dd mkdir curl'
+ CURL_BIN=curl
+ which sed basename date grep stat dd mkdir curl
+ [[ 0 != 0 ]]
+ which readlink
+ [[ 0 == 0 ]]
++ readlink -m //test
+ [[ /test == \/\t\e\s\t ]]
+ HAVE_READLINK=1
+ builtin printf ''
+ [[ 0 == 0 ]]
+ PRINTF='builtin printf'
+ PRINTF_OPT='-v o'
+ [[ -e /root/.dropbox_uploader ]]
+ source /root/.dropbox_uploader
+ [[ '' != '' ]]
+ [[ '' != '' ]]
+ [[ this is the token = '' ]]
+ COMMAND=
+ ARG1=
+ ARG2=
+ let argnum=1-2
+ case $COMMAND in
+ [[ '' != '' ]]
+ usage
+ echo -e 'Dropbox Uploader v1.0'
Dropbox Uploader v1.0
+ echo -e 'Andrea Fabrizi - andrea.fabrizi@gmail.com\n'

thanks very much.
asis

**Comment by asisrodriguezntdhoy** [comment]
sorry and SOLVED. was my mistake and install in /root instead /home/mypersonalfolder/
thanks very much for the app and for the patient
works very fine and solve my cloud problems.
asis
