### ISSUE TITLE
Skip files speed

### ISSUE THREAD

**Issue by beserious** [andreafabrizi/Dropbox-Uploader#330]
Hi
I have almost 300K files and need to take backup daily and daily almost 250 files are added., But when I used -s option to skip already uploaded files it worked too slow, takes same time as downloading file ( just bit less may be )... so is there any way I can speed this up?

**Comment by ricyoung** [comment]
I am having a similar issue, but with mine, the files I upload are very large over 30gigs per one file, and when I use the -s option it reloads them.

**Comment by andreafabrizi** [comment]
With the -s option the script will check if the remote file exists before uploading it again. This means that a new HTTP request has to be made, and it probably slow down all the process, but there's no other way.

**Comment by beserious** [comment]
so can there be any option like it will take most recent file from the particular folder?

**Comment by andreafabrizi** [comment]
Not for the moment.
