### ISSUE TITLE
Can't list/download all files in a folder

### ISSUE THREAD

**Issue by towerleung** [andreafabrizi/Dropbox-Uploader#331]
Hi,

I used the -s flag to download only the updated/new files from a dropbox folder and other than skipping those existing files it doesn't download those new/updated files. I then used the 'list' parameter trying to list out all the files in the folder but after listing about 1/3 of the files it stopped. Could you please advise how should I tackle this issue?  Thank you very much!

Regards,
Tower.L

**Comment by andreafabrizi** [comment]
Please send me the output of the script in debug mode (-d)

**Comment by towerleung** [comment]
Truly sorry for the late response, attached is the debug log. 


[dropbox_uploader_debug.txt](https://github.com/andreafabrizi/Dropbox-Uploader/files/545514/dropbox_uploader_debug.txt)

**Comment by towerleung** [comment]
I found the below text in the debug log which seems to be abnormal:

"cursor": "AAFNKshLokJxmeO9Rdx371pEh_8mscvdDyifMAaJvP-Aell555b-yr_v5j3q3dDVTSBD3C3ZnTDGmvBsYtixhxqZwXrAf-B2IGWil3SQIZ2m5riDakVQgWvFaAVitJwu_B-DVB2DiPKrJiP7TblKlpakLDkx2urd8xKep4JEF98c1w", "has_more": true}'

**Comment by andreafabrizi** [comment]
First of all you forgot to remove your token from the log, so I advise you to revoke it if you don't want other people access your dropbox.

About the issue, In the debug log I see only the download command, not the list, and I understood that your problem is that the list command doesn't complete correctly.

**Comment by towerleung** [comment]
Thank you so much for reminding and I have revoked the app token. 

Actually the issue symptom is same for both list and download, I have phone camera photos automatically backed up to the folder but the script can only list/download the photos up to may 2016. Must I upload the List command log file?

**Comment by towerleung** [comment]
Here comes the "List' log.

**Comment by towerleung** [comment]
Here comes the 'List" log. Thank you very much!

**Comment by towerleung** [comment]
Here comes the "List" log. Thanks a lot!
[list.txt](https://github.com/andreafabrizi/Dropbox-Uploader/files/558227/list.txt)

**Comment by andreafabrizi** [comment]
Should be fixed!
