### ISSUE TITLE
Exiting

### ISSUE THREAD

**Issue by IamC8** [andreafabrizi/Dropbox-Uploader#332]
Hi. I have a bash script that does backups and call your code to upload to dropbox.
The code is:
. /home/pi/scripts/dropbox_uploader.sh -s upload /home/pi/Dropbox/current/noChange/scanner/* /currentFiles/noChange/
. /home/pi/scripts/dropbox_uploader.sh upload /home/pi/Dropbox/current/doChange/scanner/* /currentFiles/doChange/

The script (your code) exits after the first line, and the second line is never reached.
Please suggest what I should do.

Regards

**Comment by andreafabrizi** [comment]
Try removing the  ". " before the script path, just use:
 ```/home/pi/scripts/dropbox_uploader.sh -s upload /home/pi/Dropbox/current/noChange/scanner/* /currentFiles/noChange/```
