### ISSUE TITLE
Upload existing files

### ISSUE THREAD

**Issue by MikaelLind** [andreafabrizi/Dropbox-Uploader#333]
What happens if I try to upload a huge folder contains images and sub folders, will it only upload new files and folders or will it upload everything?

The same with the download job, will it just download images in the folder that doesn't already exists?

Thanks!

**Comment by andreafabrizi** [comment]
If you use the -s option, file which already exists are not uploaded/downloaded again.

**Comment by MikaelLind** [comment]
How will it determine that? Is it file name? Modification time?

My question is more how it will handle if I change the content of a file without changing the files name. Will it skip it if I use the -s option?
