### ISSUE TITLE
Can't upload

### ISSUE THREAD

**Issue by attiqfsd** [andreafabrizi/Dropbox-Uploader#334]
I am trying to upload and it is showing this error

Dropbox-Uploader]# ./dropbox_uploader.sh upload ../courses/seofundamentals.zip courses/seofundamentals.zip
 > Uploading "/root/courses/seofundamentals.zip" to "/courses/seofundamentals.zip"*** FAILED
An error occurred requesting /chunked_upload

When I ran the uploaded for the first time it only took the api key of the app and not the secret key. How can I remove it completely and install it again from start?

**Comment by andreafabrizi** [comment]
Plase read the README before asking.

**Comment by attiqfsd** [comment]
I read the Readme file before installing and before asking as well. I tried using both git and curl method of installing the script.

**Comment by andreafabrizi** [comment]
You asked "How can I remove it completely and install it again from start?". The answer is in the readme or in the help: use the **unlink** command.

**Comment by attiqfsd** [comment]
Thanks. I was able to unlink my account from the script. I ran the script to relink and created a new app in my Dropbox account. The script is asking for app token. In what format I will have to input the app key and app secret? 
Is it like app-key/app-secret or is there some other way to enter it?

**Comment by andreafabrizi** [comment]
Why do you want to input the app key and secret? Just provide the app token as requested.

**Comment by attiqfsd** [comment]
Thanks. I was able to figure it out :)
