### ISSUE TITLE
'An error occurred requesting /upload\n'

### ISSUE THREAD

**Issue by genemoore42** [andreafabrizi/Dropbox-Uploader#335]
I just re-installed dropbox_uploader on a fresh install of Raspbian (on a Pi2). The upload functionality is throwing an error. (Please note: I can use other uploader.sh functions such as list to gain access to my dropbox folder so am assuming there is not problem with my auth token). Any suggestions for correcting this problem would be appreciated. Also, is there a way to input a new auth token for a newly created app on dropbox? when I removed the folder (sudo rm -r Dropbox-Uploader) and re-installed it did not prompt me for a new access token.

Content of -d debug output:

sudo ./dropbox_uploader.sh -d -p upload /home/krishna/Pictures/image1.jpg image1.jpg
1.0
Linux harekrishna 4.4.26-v7+ #915 SMP Thu Oct 20 17:08:44 BST 2016 armv7l GNU/Linux
Raspbian GNU/Linux 8 \n \l

+ RESPONSE_FILE=/tmp/du_resp_debug
+ [[ '' == '' ]]
+ BIN_DEPS='sed basename date grep stat dd mkdir curl'
+ CURL_BIN=curl
+ which sed basename date grep stat dd mkdir curl
+ [[ 0 != 0 ]]
+ which readlink
+ [[ 0 == 0 ]]
++ readlink -m //test
+ [[ /test == \/\t\e\s\t ]]
+ HAVE_READLINK=1
+ builtin printf ''
+ [[ 0 == 0 ]]
+ PRINTF='builtin printf'
+ PRINTF_OPT='-v o'
+ [[ -e /root/.dropbox_uploader ]]
+ source /root/.dropbox_uploader
+ [[ '' != '' ]]
+ [[ '' != '' ]]
+ [[ _auth token removed_ = '' ]]
+ COMMAND=upload
+ ARG1=/home/krishna/Pictures/image1.jpg
+ ARG2=image1.jpg
+ let argnum=5-3
+ case $COMMAND in
+ [[ 2 -lt 2 ]]
+ FILE_DST=image1.jpg
+ (( i=3+1 ))
+ (( i<5 ))
+ FILE_SRC=/home/krishna/Pictures/image1.jpg
+ db_upload /home/krishna/Pictures/image1.jpg /image1.jpg
++ normalize_path /home/krishna/Pictures/image1.jpg
+++ builtin printf /home/krishna/Pictures/image1.jpg
++ path=/home/krishna/Pictures/image1.jpg
++ [[ 1 == 1 ]]
+++ readlink -m /home/krishna/Pictures/image1.jpg
++ new_path=/home/krishna/Pictures/image1.jpg
++ [[ g == \/ ]]
++ echo /home/krishna/Pictures/image1.jpg
+ local SRC=/home/krishna/Pictures/image1.jpg
++ normalize_path /image1.jpg
+++ builtin printf /image1.jpg
++ path=/image1.jpg
++ [[ 1 == 1 ]]
+++ readlink -m /image1.jpg
++ new_path=/image1.jpg
++ [[ g == \/ ]]
++ echo /image1.jpg
+ local DST=/image1.jpg
+ [[ ! -e /home/krishna/Pictures/image1.jpg ]]
+ [[ ! -r /home/krishna/Pictures/image1.jpg ]]
++ db_stat /image1.jpg
+++ normalize_path /image1.jpg
++++ builtin printf /image1.jpg
+++ path=/image1.jpg
+++ [[ 1 == 1 ]]
++++ readlink -m /image1.jpg
+++ new_path=/image1.jpg
+++ [[ g == \/ ]]
+++ echo /image1.jpg
++ local FILE=/image1.jpg
++ [[ /image1.jpg == \/ ]]
++ curl -X POST -L -s --show-error --globoff -i -o /tmp/du_resp_debug --header 'Authorization: Bearer **_auth token removed_**' --header 'Content-Type: application/json' --data '{"path": "/image1.jpg"}' https://api.dropboxapi.com/2/files/get_metadata
++ check_http_response
++ CODE=0
++ case $CODE in
++ grep -q 'HTTP/1.1 400' /tmp/du_resp_debug
+++ sed -n 's/{".tag": *"*\([^"]*\)"*.*/\1/p' /tmp/du_resp_debug
++ local TYPE=
++ case $TYPE in
++ echo ERR
+ TYPE=ERR
+ [[ ERR == \F\I\L\E ]]
+ [[ ERR == \E\R\R ]]
+ [[ g != \/ ]]
+ DST=/image1.jpg
+ [[ -d /home/krishna/Pictures/image1.jpg ]]
+ [[ -e /home/krishna/Pictures/image1.jpg ]]
+ db_upload_file /home/krishna/Pictures/image1.jpg /image1.jpg
++ normalize_path /home/krishna/Pictures/image1.jpg
+++ builtin printf /home/krishna/Pictures/image1.jpg
++ path=/home/krishna/Pictures/image1.jpg
++ [[ 1 == 1 ]]
+++ readlink -m /home/krishna/Pictures/image1.jpg
++ new_path=/home/krishna/Pictures/image1.jpg
++ [[ g == \/ ]]
++ echo /home/krishna/Pictures/image1.jpg
+ local FILE_SRC=/home/krishna/Pictures/image1.jpg
++ normalize_path /image1.jpg
+++ builtin printf /image1.jpg
++ path=/image1.jpg
++ [[ 1 == 1 ]]
+++ readlink -m /image1.jpg
++ new_path=/image1.jpg
++ [[ g == \/ ]]
++ echo /image1.jpg
+ local FILE_DST=/image1.jpg
+ shopt -s nocasematch
++ basename /image1.jpg
+ basefile_dst=image1.jpg
+ [[ image1.jpg == \t\h\u\m\b\s\.\d\b ]]
+ [[ image1.jpg == \d\e\s\k\t\o\p\.\i\n\i ]]
+ [[ image1.jpg == \.\d\s\_\s\t\o\r\e ]]
+ [[ image1.jpg == \i\c\o\n\\\r ]]
+ [[ image1.jpg == \.\d\r\o\p\b\o\x ]]
+ [[ image1.jpg == \.\d\r\o\p\b\o\x\.\a\t\t\r ]]
+ shopt -u nocasematch
++ file_size /home/krishna/Pictures/image1.jpg
+++ stat --format=%s /home/krishna/Pictures/image1.jpg
++ SIZE=612039
++ '[' 0 -eq 0 ']'
++ echo 612039
++ return
+ FILE_SIZE=612039
++ db_stat /image1.jpg
+++ normalize_path /image1.jpg
++++ builtin printf /image1.jpg
+++ path=/image1.jpg
+++ [[ 1 == 1 ]]
++++ readlink -m /image1.jpg
+++ new_path=/image1.jpg
+++ [[ g == \/ ]]
+++ echo /image1.jpg
++ local FILE=/image1.jpg
++ [[ /image1.jpg == \/ ]]
++ curl -X POST -L -s --show-error --globoff -i -o /tmp/du_resp_debug --header 'Authorization: Bearer **_auth token removed_**' --header 'Content-Type: application/json' --data '{"path": "/image1.jpg"}' https://api.dropboxapi.com/2/files/get_metadata
++ check_http_response
++ CODE=0
++ case $CODE in
++ grep -q 'HTTP/1.1 400' /tmp/du_resp_debug
+++ sed -n 's/{".tag": *"*\([^"]*\)"*.*/\1/p' /tmp/du_resp_debug
++ local TYPE=
++ case $TYPE in
++ echo ERR
+ TYPE=ERR
+ [[ ERR != \E\R\R ]]
+ [[ 612039 -gt 157286000 ]]
+ db_simple_upload_file /home/krishna/Pictures/image1.jpg /image1.jpg
++ normalize_path /home/krishna/Pictures/image1.jpg
+++ builtin printf /home/krishna/Pictures/image1.jpg
++ path=/home/krishna/Pictures/image1.jpg
++ [[ 1 == 1 ]]
+++ readlink -m /home/krishna/Pictures/image1.jpg
++ new_path=/home/krishna/Pictures/image1.jpg
++ [[ g == \/ ]]
++ echo /home/krishna/Pictures/image1.jpg
+ local FILE_SRC=/home/krishna/Pictures/image1.jpg
++ normalize_path /image1.jpg
+++ builtin printf /image1.jpg
++ path=/image1.jpg
++ [[ 1 == 1 ]]
+++ readlink -m /image1.jpg
++ new_path=/image1.jpg
++ [[ g == \/ ]]
++ echo /image1.jpg
+ local FILE_DST=/image1.jpg
+ [[ 1 == 1 ]]
+ [[ 0 == 0 ]]
+ CURL_PARAMETERS=--progress-bar
+ LINE_CR='\n'
+ print ' > Uploading "/home/krishna/Pictures/image1.jpg" to "/image1.jpg"... \n'
+ [[ 0 == 0 ]]
+ echo -ne ' > Uploading "/home/krishna/Pictures/image1.jpg" to "/image1.jpg"... \n'
 > Uploading "/home/krishna/Pictures/image1.jpg" to "/image1.jpg"... 
+ curl --progress-bar -X POST -i --globoff -o /tmp/du_resp_debug --header 'Authorization: Bearer **_auth token removed_**' --header 'Dropbox-API-Arg: {"path": "/image1.jpg","mode": "overwrite","autorename": true,"mute": false}' --header 'Content-Type: application/octet-stream' --data-binary @/home/krishna/Pictures/image1.jpg https://content.dropboxapi.com/2/files/upload
######################################################################## 100.0%
+ check_http_response
+ CODE=0
+ case $CODE in
+ grep -q 'HTTP/1.1 400' /tmp/du_resp_debug
+ grep -q '^HTTP/1.1 200 OK' /tmp/du_resp_debug
+ print 'FAILED\n'
+ [[ 0 == 0 ]]
+ echo -ne 'FAILED\n'
FAILED
+ print 'An error occurred requesting /upload\n'
+ [[ 0 == 0 ]]
+ echo -ne 'An error occurred requesting /upload\n'
An error occurred requesting /upload
+ ERROR_STATUS=1
+ (( i++  ))
+ (( i<5 ))
+ remove_temp_files
+ [[ 1 == 0 ]]
+ exit 1

Content of /tmp/du_resp/debug:

HTTP/1.1 100 Continue

HTTP/1.1 500 Internal Server Error
Server: nginx
Date: Wed, 26 Oct 2016 22:56:30 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Dropbox-Request-Id: 9b7b47b561a8c62bd61962af8ec1f97b
X-Robots-Tag: noindex, nofollow, noimageindex

**Comment by barbalex** [comment]
@genemoore42 I have same error message. You closed this issue. Why? How could you resolve the issue?

**Comment by bob10818** [comment]
I have exactly the same issue. Python program was working fine previously before the APIv2 upgrade. Loaded new Pi 2 with latest Raspian, loaded latest Dropbox-Uploader, ran .dropbox_uploader.sh and got Access Token as requested.
Ran test  .dropbox_uploader.sh upload ...., which worked fine - test file on Dropbox as expected.
But when I call the shell from my Python program I get the message "An error occurred requesting /upload". Debug file attached. I am trying to send a jpg file to a new (to be created) folder on dropbox, which worked before.

[debug file.txt](https://github.com/andreafabrizi/Dropbox-Uploader/files/1447202/debug.file.txt)

In the previous incarnation, I was asked for the Access key and Secret key when I first ran the program. That doesn't happen any more. But the "Authorization: Bearer ....." looks like one of those keys, but not one I have seen before.

**Comment by bob10818** [comment]
[DB Uploader debug.txt](https://github.com/andreafabrizi/Dropbox-Uploader/files/1461874/DB.Uploader.debug.txt)
This is driving me mad. It started working perfectly yesterday. Now today it fails every time. Attached the latest debug output. 
If I run dropbox_uploader.sh or dropShell.sh from the command line, it works fine, so I assume the access token is OK. But when I run dropbox_uploader.sh through a subprocess call in my Python program, it fails. But it worked yesterday!!!
 I've tried rebooting the computer, reloaded Dropbox-Uploader, deleted the ~/.dropbox-uploader file with the Auth Key, created a new App and reset the key. Interestingly, if I run from the shell after deleting the Auth key, it asks to create a new app and key, but not if run through the Python program.
Is there another config file or something I need to delete and rebuild?

**Comment by bob10818** [comment]
Ah, I think I have the answer - I had trailing spaces in some of the directory names. Either Dropbox or the Uploader didn't like this, and it now works with the spaces stripped out. 
I have to say, the error message is not entirely helpful. I spent ages trying to resolve authentication and all kinds of other issues which didn't exist.
