### ISSUE TITLE
Previously shared files return an error

### ISSUE THREAD

**Issue by macbrownzie** [andreafabrizi/Dropbox-Uploader#337]
When using the dropbox_uploader.sh share (file) on a file that has already been shared, it returns an error, instead of just listing the existing share link. 

We can use the https://dropboxapi.com/2/sharing/list_shared_links to request the existing share link and return it instead of the error.

**Comment by macbrownzie** [comment]
Here is a patch to dropbox_uploader.sh to correct the issue.   I don't have permissions to submit it as a fork / pull. 

59a60
> API_SHARE_LIST="https://api.dropboxapi.com/2/sharing/list_shared_links"
1273a1275,1295
>     else
>         get_Share "$FILE_DST" 
>     fi
> }
> 
> 
> # Existing Shared Link
> #$1 = Remote file
> function get_Share
> {
>     local FILE_DST=$(normalize_path "$1")
> 
>     $CURL_BIN $CURL_ACCEPT_CERTIFICATES -X POST -L -s --show-error --globoff -i -o "$RESPONSE_FILE" --header "Authorization: Bearer $OAUTH_ACCESS_TOKEN" --header "Content-Type: application/json" --data "{\"path\": \"$FILE_DST\"}" "$API_SHARE_LIST"
>     check_http_response
> 
>     #Check
>     if grep -q "^HTTP/1.1 200 OK" "$RESPONSE_FILE"; then
>         print " > Share link: "
>         SHARE_LINK=$(sed -n 's/.*"url": "\([^"]*\).*/\1/p' "$RESPONSE_FILE")
>         echo "$SHARE_LINK"
>

**Comment by jslee777** [comment]
After I wrote the token of Dropbox, I can't do anything including upload, download and so on.
example:  Creating Directory "/abc"... FAILED

How can I change the token or change the Dropbox token.

**Comment by LeRondPoint** [comment]
Do you think you could format that properly @macbrownzie ?

**Comment by brenwell** [comment]
has anyone got this working, that would be awesome

**Comment by andreafabrizi** [comment]
Fixed
