### ISSUE TITLE
Error from `share` : shared_link_already_exists

### ISSUE THREAD

**Issue by dudeinthemirror** [andreafabrizi/Dropbox-Uploader#342]
Is there a way to get the existing shared link instead of this error:

```
./dropbox_uploader.sh share /android/builder.20161205.android.log
FAILED
 > Error: shared_link_already_exists/
```

**Comment by brenwell** [comment]
+1

**Comment by JavidPack** [comment]
I would like this too, or rather some easy way of checking if the file already has been shared or not.

**Comment by ffes** [comment]
https://www.dropbox.com/developers/documentation/http/documentation#sharing-list_shared_links

**Comment by andreafabrizi** [comment]
Fixed
