### ISSUE TITLE
Homepage link doesn't go to "dropbox uploader" specific page

### ISSUE THREAD

**Issue by ilovezfs** [andreafabrizi/Dropbox-Uploader#345]
This repository's description displays http://www.andreafabrizi.it/?dropbox_uploader as the homepage. However that now ends up going to the same location as just https://www.andreafabrizi.it/ without the `?dropbox_uploader`. I'm assuming there was some kind of breaking change in the backend that causes `?dropbox_uploader ` not to work as expected anymore.

**Comment by andreafabrizi** [comment]
@ilovezfs, that's is true! Fixed, thanks!

**Comment by ilovezfs** [comment]
Thanks!
