### ISSUE TITLE
Feature request: recursive list

### ISSUE THREAD

**Issue by affvalente** [andreafabrizi/Dropbox-Uploader#354]
Recursive list, using API v2

https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder

recursive Boolean If true, the list folder operation will be applied recursively to all subfolders and the response will contain contents of all subfolders. The default for this field is False.

Many thanks!
andre

**Comment by TeXtnik** [comment]
I think is would be a nice feature. I have upload 16 GB of files and I would like to check if dropbox has every file I have upload. For this, a list (like the Unix `tree` command) of all the files below a  directory is mandatory.
