### ISSUE TITLE
upload to dropbox failed, error: "curl: option --data-binary: out of memory"

### ISSUE THREAD

**Issue by tracking** [andreafabrizi/Dropbox-Uploader#363]
I use a small memory vps, file size is almost 50M
``` 
> Uploading "/home/blog/backup/20170407_171845_UTC/www.zip" to "/backup/20170407_171845_UTC/www.zip"... curl: option --data-binary: out of memory
curl: try 'curl --help' or 'curl --manual' for more information
FAILED
An error occurred requesting /upload
```

**Comment by andreafabrizi** [comment]
What you can do is:

- Find the code "if [[ $FILE_SIZE -gt 157286000 ]]; then" and change the 157286000 to 5000000 (5M) for example
- At the beginning of the script set CHUNK_SIZE to 5
In this way, if the file is greater than 5Mb, it will upload it in chunks of 5MB, using maximum 5M or RAM for every chunk. It should work and you can still reduce the value.

**Comment by metorm** [comment]
This solves my problem on my tiny VPS with 128M RAM, thanks a lot!
