### ISSUE TITLE
Suggestion to improve READ.me

### ISSUE THREAD

**Issue by gerardwr** [andreafabrizi/Dropbox-Uploader#364]
The script works great, thanks for sharing.

I would like to suggest to remove the $ signs in these commands in the READ.me. I Copied the lines to my Raspberry, but the $ sign is not part of a valid command and leads to an error. Friend of mine made the  same mistake.
 $chmod +x dropbox_uploader.sh
 $./dropbox_uploader.sh

Thanks.

**Comment by andreafabrizi** [comment]
the $ is widely used to indicate that it's a shell command.
