### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by canuckbrian** [andreafabrizi/Dropbox-Uploader#366]
Hello,

I am using your script to backup some MySQL databases to my Dropbox account that have been dumped and compressed using 7zip. The script works perfectly in the sense that it uploads the files to my dropbox as I wanted. My complaint though is with the speed at which it syncs.

My MySQL server has a Cron job that runs every hour on the hour to backup my databases. The backup script creates a folder for every Year, Month, Day, Database. Eg: "/root/DB_Backups/2017/04-Apr/14/mydatabase", then inside the folder for the database it creates the .7z archive files from every hour. Eg: The 8am back would be "/root/DB_Backups/2017/04-Apr/14/mydatabase/mydatabase-0800.7z". Then at 5 minutes after every hour I have a Cron job that runs your script and uploads the new files to my Dropbox. I'm using the following command: "5 * * * * sh /root/dropbox_uploader.sh -q -s upload DB_Backups/ /". The problem I'm having is that your script takes a long time to process through all the existing folders and files and skip what's already there. There's almost a full second delay between each folder / file it checks. It's not an upload speed issue as these backups are only about 20KB each.

My concern is that after time the file and folder structure will be so large that it will take longer than the 55 minutes left in the hour to run the Dropbox upload script because of how long it takes to move through the existing files / folders. Already with about a day and a half of backups for two databases there's 36 files spread between 4 folders and the script is already taking almost a minute to complete.

Is there any way to speed up the process? Maybe create a local cache of the remote Dropbox folders/files when the script starts, compare that to the selected local folders/files and only upload folders/files that aren't in the remote Dropbox. That way the check isn't done remotely per file/folder, but instead done locally?

**Comment by andreafabrizi** [comment]
Yes actually is like this, as it's a script it can't keep an alive connection to the server, so for each file it make a new connection using the curl command, and this can take time of course.

**Comment by DWhettam** [comment]
If anyone else is having this issue, you can resolve it by using `./dropbox_uploader. list [directory]` to get the currently uploaded files.  Then loop over your files and check they are not in the list before uploading. You'll probably need to do some string formatting and nesting loops depending on your file structure, but the basic check is quite simple. That way you only need to query dropbox once to get the uploaded files, instead of querying it for every file, giving a significant speedup.
