### ISSUE TITLE
Updating the api? 

### ISSUE THREAD

**Issue by rivaflush** [andreafabrizi/Dropbox-Uploader#369]
Hello,

How do you re-run the config after already entering the api?  I had to destroy my app and i'd rather edit the file than destroy the directory and re-download it.  

Other suggestions are welcome! :) 

Thanks for the awesome script btw!

**Comment by Ruok2bu** [comment]
In the folder where dropbox_uploader.sh resides, delete the file named .dropbox_uploader

**Comment by andreafabrizi** [comment]
There's an appropriate option, just read the README.
