### ISSUE TITLE
Uploads to the same file 

### ISSUE THREAD

**Issue by chrysnik** [andreafabrizi/Dropbox-Uploader#372]
Hi,

When trying to upload a series of files it uploads them one by one but the output file is dropbox is the same. So it overwrites continuously the same file. 

Entry: 
./dropbox_uploader.sh upload /home/homeassistant/.homeassistant/ "star.star"
_("star.star" are the characters / but are redacted in this board)_

Output: 
 > Uploading "/home/homeassistant/.homeassistant/configuration.yaml" to "/home/homeassistant/.homeassistant/**tradfri.conf**"... DONE
 > Uploading "/home/homeassistant/.homeassistant/groups.yaml" to "/home/homeassistant/.homeassistant/**tradfri.conf**"... DONE
 > Uploading "/home/homeassistant/.homeassistant/home-assistant.log" to "/home/homeassistant/.homeassistant/**tradfri.conf**"... DONE

The output file is not always the same

**Comment by andreafabrizi** [comment]
Probably you forgot the destination folder.
The correct syntax is:
`./dropbox_uploader.sh upload /path/to/star.star /dest/`
