### ISSUE TITLE
Support for loading settings from an environment variable or -c config file

### ISSUE THREAD

**Issue by graingert** [andreafabrizi/Dropbox-Uploader#38]
I'd like to use dropbox uploader as part of my Travis-CI build script and Travis allows environment variables and files to be encrypted with their public key.

I'd like to be able to use a var like:

``` bash
DROPBOX_UPLOADER=<appkey>,<appsecret>,<access_level>,<oauth_atoken>,<oauth_atoken_secret>
```

**Comment by cybertk** [comment]
Reopened with PR #264
