### ISSUE TITLE
Incorrectly entered Access Token - Reinitiating the configuration wizard

### ISSUE THREAD

**Issue by electricwizard84** [andreafabrizi/Dropbox-Uploader#396]
Hi, 

I accidentally entered an incorrect Access Token and now i am struggling to bring up the wizard to repeat the process. 

I've also tried to repeat the installation in an effort to re-initiate the configuration but this has failed. 

Any ideas would be helpful. 

Regards, 
Matthew Lee

**Comment by Paul-Reed** [comment]
Just delete your existing access token key, and the next time you run dropbox-uploader it will bring up the wizard.
Look for a hidden file .dropbox_uploader possibly saved /home/pi/.dropbox_uploader

**Comment by electricwizard84** [comment]
Thanks Paul. Much appreciated.

**Comment by andreafabrizi** [comment]
You can also use the **unlink** command.
