### ISSUE TITLE
Get Error: path/not_found/ but the path is correct

### ISSUE THREAD

**Issue by nikitavoloboev** [andreafabrizi/Dropbox-Uploader#398]
I have a file in my `~Dropbox` folder. I have setup Dropbox-Uploader correctly and try to run it like :  

`./dropbox_uploader.sh share "~/Dropbox/img.png"` but I get this error when running the command : 

```Bash
FAILED
 > Error: path/not_found/.
```

Really not sure why. Thank you for any help.

**Comment by nikitavoloboev** [comment]
However if I move the script itself to Dropbox folder and then run it from there, it works. Seems I can't call this script on files from outside Dropbox.

Is there any way to avoid this?

**Comment by MegaV0lt** [comment]
Try not using " because of wxpasion of ~
`darkwing@darkwing-pc / $ tst=~/ ; ls $tst
Bilder              Finanzen.ffs_gui                 Schreibtisch
channeledit.conf    KeePassXC-2.2.0-x86_64.AppImage  Steam
Dokumente           Musik                            SyncSettings.ffs_gui
Downloads           Öffentlich                       trusted.gpg.d.save
EasyWebitor         Paketlisten.tar.xz               trusted-keys.gpg
epgsearch           PlayOnLinux's virtual drives     Videos
Finanzen.ffs_batch  Release.key                      Vorlagen
darkwing@darkwing-pc / $ tst="~/" ; ls $tst
ls: Zugriff auf '~/' nicht möglich: Datei oder Verzeichnis nicht gefunden
`
Second Call fails because of "

**Comment by nikitavoloboev** [comment]
Still getting errors : 

```Bash
~/Dropbox
❯ ./upload.sh share ~/Dropbox/hello.png
FAILED
 > Error: path/not_found/...

~/Dropbox
❯ ./upload.sh share /Users/nikivi/Dropbox/hello.png
FAILED
 > Error: path/not_found/..

~/Dropbox
❯
```

**Comment by MegaV0lt** [comment]
Sure that the path is correct?
what gives 
`pwd`

**Comment by shrimpwagon** [comment]
It's just broken. I'm getting the same problem:

    bash dropbox_uploader.sh list "App"
     > Listing "/App"... FAILED

    cat /tmp/du_resp_debug
    HTTP/1.1 409 Conflict
    Server: nginx
    Date: Tue, 03 Oct 2017 14:36:24 GMT
    Content-Type: application/json
    Transfer-Encoding: chunked
    Connection: keep-alive
    X-Dropbox-Request-Id: 3d4b51ac41a77fdedf62d3f1b1c5f277
    X-Frame-Options: DENY
    Content-Security-Policy: sandbox; frame-ancestors 'none'
    X-Content-Type-Options: nosniff
    Content-Disposition: attachment; filename='error'
    
    {"error_summary": "path/not_found/", "error": {".tag": "path", "path": {".tag": "not_found"}}}

**Comment by andreafabrizi** [comment]
It works for me. 
I've created a folder **~Dropbox** containing a file:

```
$ ./dropbox_uploader.sh list "~Dropbox"
 > Listing "/~Dropbox"... DONE
 [F] 8453472 RaspBkp_01-04-2015_0400.tar.gz
$ ./dropbox_uploader.sh share "~Dropbox/RaspBkp_01-04-2015_0400.tar.gz"
 > Share link: https://www.dropbox.com/s/xxxxxxxxxxx/RaspBkp_01-04-2015_0400.tar.gz?dl=0
```

**Comment by nikitavoloboev** [comment]
For me this fails. I have the file inside `~/Dropbox/Shares` and I run the script:

```bash
~/Dropbox/Scripts
❯ ./upload.sh share "/Users/nikivi/Dropbox/Shares/km-macros"

FAILED
 > Error: path/not_found/
```

The file (folder actually) is certainly inside Shares dir but the script fails with: 
`Error: path/not_found/`

I don't understand why.

**Comment by necmettin** [comment]
Did you try removing Dropbox root folder? Try "Shares/km-macros" instead of "/Users/nikivi/Dropbox/Shares/km-macros"?

**Comment by nikitavoloboev** [comment]
Thank you @necmettin, this worked 🎊
