### ISSUE TITLE
Interface to Dropbox changed?

### ISSUE THREAD

**Issue by nnako** [andreafabrizi/Dropbox-Uploader#400]
Hi,

I normally used this line of bash command to get the listing of one of my dropbox folders:

`/home/pi/APP__dropbox_uploader/dropbox_uploader.sh list "/_maps"`

but since a couple of hours / maybe some days, I just get this response:

` > Listing "/_maps"... FAILED`

I searched the internet for up-to-date information about DROPBOX, but couldn't find anything to back up my suggestion that they have changed their interface. The original DROPBOX functionality on my Windows computer, which I use together with a regular client application seems to work properly. There are no errors displayed within the log.

Does anybody know something about such a thing? Are there any insider news?

**Comment by ahmeier** [comment]
I have the exact same problem, started today I think.

**Comment by ahmeier** [comment]
I figured it out. You need to download the most recent script, the authentication process has changed. I was using an old version, and I assume dropbox disabled the old authentication method today, October 1st 2017. After downloading and re-registering, copying the OAUTH 2 Access token everything works fine. Hope this helps.

**Comment by nnako** [comment]
Great. Thanks. It was, as you said.

Here the sequence for other users to update in case they didn't do it, yet:

[on LINUX]
- **`cd <appfolder>`**  will cd into your local application repo
- **`git pull`**  will pull the current source from the remote repo
- **`cd ~`**  will cd into your home directory
- **`mv .dropbox_uploader .dropbox_uploader__OLD`**  will rename / remove existing auth info
- **`cd <appfolder>`**  will cd back into your local application repo
- **`./dropbox_uploader.sh`**  will start the dropbox_updater to re-authenticate
- follow the instructions on the screen in order to get the **`access token`** and insert it

**Comment by ahmeier** [comment]
nice bullet list nnako. Probably this issue can be closed.
