### ISSUE TITLE
An error occurred requesting /chunked_upload

### ISSUE THREAD

**Issue by lukinko** [andreafabrizi/Dropbox-Uploader#405]
I think this line 
https://github.com/andreafabrizi/Dropbox-Uploader/blob/master/dropbox_uploader.sh#L607
        let OFFSET=$OFFSET+$CHUNK_REAL_SIZE

should be in "if 200 OK check" in eg 612 line

Because in case of an error we should once again upload the same chunk

**Comment by AlexanderBurdenko** [comment]
Is this error can corrupt files when i upload to Dropbox ?
Thank you

**Comment by andreafabrizi** [comment]
Thanks!
