### ISSUE TITLE
dont work anymore ...

### ISSUE THREAD

**Issue by guy88** [andreafabrizi/Dropbox-Uploader#406]
Hello

I use the script for quite some time, I have not changed anything and ....

` https://api.dropbox.com/1/oauth/request_token
+ check_http_response
+ CODE=0
+ case $CODE in
+ grep -q 'HTTP/1.1 400' /tmp/du_resp_debug
++ sed -n -e 's/{"error": "\([^"]*\)"}/\1/p' /tmp/du_resp_debug
+ ERROR_MSG=v1_retired
+ case $ERROR_MSG in
++ sed -n 's/oauth_token_secret=\([a-z A-Z 0-9]*\).*/\1/p' /tmp/du_resp_debug
+ OAUTH_TOKEN_SECRET=
++ sed -n 's/.*oauth_token=\([a-z A-Z 0-9]*\)/\1/p' /tmp/du_resp_debug
+ OAUTH_TOKEN=
+ [[ '' != '' ]]
+ echo -ne ' FAILED\n\n Please, check your App key and secret...\n\n'
 FAILED

 Please, check your App key and secret...

+ remove_temp_files
+ [[ 1 == 0 ]]
+ exit 1
could you help me ?`

**Comment by fberoiza** [comment]
I have de the same problem.
The script doesnt work.

**Comment by andreafabrizi** [comment]
This is because the v1 API has been deprecated. Please use the latest version of the script, you will be asked to setup it again. Or, if not, just try the **unlink** command.
