### ISSUE TITLE
Re-asks for token

### ISSUE THREAD

**Issue by GitHubGreg** [andreafabrizi/Dropbox-Uploader#422]
Thanks for writing an sharing this great tool. I've been using it for over a year to send backups from my website control panel, VestaCP, to Dropbox.

However the new version (January 2018 commits) re-asks for my token every time I run my script. The script I use is [here](https://forum.vestacp.com/viewtopic.php?t=14123).

I don't know if this is something with my script, and if it is, then sorry for posting this as an issue. But my script worked fine with the older version (January 2017) and I am unable to see why the new version is asking for the token again when run.

**Comment by RomanBogachev** [comment]
The same error. 

I tried manually use script, it asked for a token, after entering it - get error `/root/scripts/dropbox_uploader.sh: line 1559: : No such file or directory`

Problem in line `echo "OAUTH_ACCESS_TOKEN=$OAUTH_ACCESS_TOKEN" > "$CONFIG_FILE"`

**Comment by andreafabrizi** [comment]
Config file is set to be in the user home folder:

`CONFIG_FILE=~/.dropbox_uploader`

What's the output of the command `echo ~`?

**Comment by RomanBogachev** [comment]
```
# echo ~
/root
```

**Comment by RomanBogachev** [comment]
The other script work normally with new version.

```sh
#!/bin/sh
DATE=`date "+%Y_%m_%d:%H:%M:%S"`
LOGIN="USER"  					  
PASSWORD="PASS"                        
DROPBOX_UPLOADER="/root/scripts/dropbox_uploader.sh"
DROPBOX_PATH="/"                                  
SQL_PATH="/root/database_backup/"                     
MYSQLDUMP="mysqldump"                             

databases=(DB_NAME)                    

for database in "${databases[@]}"
do
    echo "MySQL backup database: ${database}"
    $MYSQLDUMP -q -u$LOGIN -p$PASSWORD $database > ${SQL_PATH}${database}_${DATE}.sql
    gzip -9 -c ${SQL_PATH}${database}_${DATE}.sql > ${SQL_PATH}${database}_${DATE}.sql.gz
    $DROPBOX_UPLOADER upload ${SQL_PATH}${database}_${DATE}.sql.gz ${DROPBOX_PATH}${database}/${DATE}.sql.gz
    rm ${SQL_PATH}${database}_${DATE}.sql.gz
done

# удаляем все бэкапы старше 10 дней
find ${SQL_PATH} -type f -mtime +2 -exec rm -f {} \;
# архивируем бэкапы полученные более 1 дня назад
find ${SQL_PATH} -type f -mtime +1 -exec gzip -9 {} \; 2>/dev/null
```

**Comment by andreafabrizi** [comment]
Just pushed a fix. A bug was introduced by a pull request I approved last week.

**Comment by GitHubGreg** [comment]
Thanks very much for the prompt reply and fix, it is working again.
