### ISSUE TITLE
Some error occured

### ISSUE THREAD

**Issue by sakethramanujam** [andreafabrizi/Dropbox-Uploader#435]
I cloned the project on to the Raspi3 and accidentally confirmed the wrong access token.
How do I reset the config file?

When I do 
```
./dropbox_uploader.sh list
```

it returns with
```
>Listing "/"... FAILED
Some error occurred. Please check the log.
```

**Comment by hinkma** [comment]
I try change new token other project, same issue. It take use old token all time even I unlink and link again.
What to do?

**Comment by mhtrinh** [comment]
It is written in the README : 
`This configuration will be stored in ~/.dropbox_uploader`

**Comment by andreafabrizi** [comment]
Try to unlink it or manually remove the conf file.

**Comment by richardkeep** [comment]
Where is the error log located?

**Comment by mhtrinh** [comment]
There is no log currently ... Usually when there are errors, it just show up in the terminal (with all other information) so you need to scroll up your terminal and find if there are any error message. You can also run in verbose to get more information.
