### ISSUE TITLE
command to delete installation? 

### ISSUE THREAD

**Issue by hvbhome** [andreafabrizi/Dropbox-Uploader#437]
HI, 
trying to cleanup my Home Assistant directories, i am uninstalling all i don't use. Dropbox-Unloader however won't let me delete the following files, cause its not authorized...

please help how to get rid of these?

/config/Dropbox-Uploader/.git/objects/pack/*.idx and8.pack

Is an uninstall command available please?
thanks,
Marius

**Comment by toshibochan** [comment]
I need this uninstall command to

**Comment by andreafabrizi** [comment]
Just run the unlink command and remove the Dropbox-Uploader folder.

**Comment by hvbhome** [comment]
unfortunately this won't work, since after unlinking, there's still no permission to deleted these files in the Dropbox-Uploader directory:

![schermafbeelding 2018-03-26 om 09 53 03](https://user-images.githubusercontent.com/33354141/37893502-80fa3efa-30db-11e8-8888-b0f57d890845.jpg)
