### ISSUE TITLE
Cant upload files

### ISSUE THREAD

**Issue by samkmk** [andreafabrizi/Dropbox-Uploader#479]
Hello, 

Im having trouble uploading files. I can upload small textfiles but "big" 5mb images can't be uploaded, the upload fails at 0.3%. What could be the problem?

Text from debugmode
+ [[ 0 == 0 ]]
+ echo -ne ' > Uploading "/home/pi/guest/1.jpg" to "/apa/guest/1.jpg"... \n'
 > Uploading "/home/pi/guest/1.jpg" to "/apa/guest/1.jpg"... 
+ curl --progress-bar -X POST -i --globoff -o /tmp/du_resp_debug --header 'Authorization: Bearer kkZgMNtf-tAAAAAAAAAACgvbNujKs1wSRn4kc5T4zNtzvfXXXXXXXXXXX' --header 'Dropbox-API-Arg: {"path": "/apa/guest/1.jpg","mode": "overwrite","autorename": true,"mute": false}' --header 'Content-Type: application/octet-stream' --data-binary @/home/pi/guest/1.jpg https://content.dropboxapi.com/2/files/upload
                                                                           0,3%
curl: (55) SSL_write() returned SYSCALL, errno = 110
+ check_http_response
+ CODE=55
+ case $CODE in
+ grep -q '^HTTP/[12].* 400' /tmp/du_resp_debug
+ grep -q '^HTTP/[12].* 200' /tmp/du_resp_debug
+ print 'FAILED\n'
+ [[ 0 == 0 ]]
+ echo -ne 'FAILED\n'
FAILED
+ print 'An error occurred requesting /upload\n'
+ [[ 0 == 0 ]]
+ echo -ne 'An error occurred requesting /upload\n'
An error occurred requesting /upload
+ ERROR_STATUS=1
+ for file in "$DIR_SRC/"*

**Comment by lucnat** [comment]
When creating the dropbox app you can choose between an app that has full access and one that only has one folder. Have you tried making one that has full access? It helped in my case.

**Comment by samkmk** [comment]
Hi again, 

I actually got it too work after a while when i switched my ISP. I had an 4G-router soulotion which was the problem in this case!
