### ISSUE TITLE
Mac OS X produces sed error

### ISSUE THREAD

**Issue by theapiarist** [andreafabrizi/Dropbox-Uploader#510]
Thank you for this really useful script. I have it installed and working well on a range of linux boxes and AWS. It also works on Mac OS X Mojave 10.14.6 but generates an error when downloading:

`sed: 1: "s/\([0-9A-F]\{2\}\)/\\x ...": bad flag in substitute command: 'I'`

This is generated from line 1503 of the current version of the script.

No errors produced uploading or listing ...

Mac OS X uses BSD sed rather than GNU sed. I think this is the problem.  

I have little understanding of shell scripting but suspect this tells the regex to ignore case? 

Is there a workaround (other perhaps than brew install gsed?) and does this matter for functionality of the script?

**Comment by tjluoma** [comment]
See https://github.com/andreafabrizi/Dropbox-Uploader/issues/378 for more info, but the quick version is this:

1. go to line 1503: 
`shaHex=$(echo $SHA_CONCAT | sed 's/\([0-9A-F]\{2\}\)/\\x\1/gI')`

2. Replace  it with this line:
`shaHex=$(echo $SHA_CONCAT | sed 's/\([0-9A-Fa-f]\{2\}\)/\\x\1/g')`

**Comment by theapiarist** [comment]
Many thanks. Now works and hashes identify identical files. Great 👍
