### ISSUE TITLE
Will Dropbox uploader be updated for new api?

### ISSUE THREAD

**Issue by kajan001** [andreafabrizi/Dropbox-Uploader#515]
Dropbox will change tokens to shortlived and most likely the legacy options will disappear by September 2021.

Will there be an update?

Info from Dropbox:

We released an update to our authorization model—you’ll want to review your app’s (Pi xxxx) permission settings, and may need to update your code for refresh tokens.
--
Action Required: Token and Permission UpdatesThe Dropbox API now supports OAuth scopes, PKCE, refresh tokens, and short-lived access tokens. We’re asking developers to review their app’s permission settings and ensure their apps support short-lived access tokens. Apps that require background access will need to update to use refresh tokens, which is made easier by using our updated SDKs.Starting September 30th, 2021, the Dropbox OAuth flow will no longer return long-lived access tokens. It will instead return short-lived access tokens, and optionally return refresh tokens. Please be sure to review, test, and move to the new permission model before then.For detailed instructions, please see:- Dropbox OAuth Guide- Blog post — Now Available: OAuth Scopes and Enhanced Permissions- Blog post — Migrating App Permissions and Access Tokens

**Comment by the-other-martin** [comment]
I'd be very interested to use it with the new authorization model! @andreafabrizi could you please adapt?

**Comment by theDiverDK** [comment]
I would really hope so as well.

**Comment by telemaxx** [comment]
#meetoo

**Comment by Terge3141** [comment]
I created a pull request to fix this problem.

**Comment by Luigi8723** [comment]
#methree

**Comment by andreafabrizi** [comment]
Merged pull request
