### ISSUE TITLE
Drop box uploader. An error occurred requesting /upload

### ISSUE THREAD

**Issue by BradMQUT** [andreafabrizi/Dropbox-Uploader#529]
Attempting a test to see if dropbox uploader is working.

I have created a test txt titled foo.txt.
When I attempt to upload with the command ./dropbox_uploader.sh upload foo.txt /
I get the following error. 

An error occurred requesting /upload
Some error occured. rerun the script with "-d" option and check the output and logfile: /tmp/du_resp_4387.

Im only new at this so Im not quite sure what Im looking at.

**Comment by charisketikidis** [comment]
Hello! I also get this error. Have you found a solution?
