### ISSUE TITLE
RasPi can't read tmp folder

### ISSUE THREAD

**Issue by Nemesis8899** [andreafabrizi/Dropbox-Uploader#60]
Hi,

I use a RasPi with the latest Debian image. Following the manual I receive below when trying to run the script for the first time. I also tried it on my Ubuntu laptop and it works like a charm.

RasPi
Debian Image Linux 7
Kernel: 3.6.11+

I done a "sudo apt-get update" and "sudo apt-get upgrade" after applying the image and also today.

Still I get below and trying to use it.

pi@raspberrypi ~ $ ./dropbox_uploader.sh 
- RESPONSE_FILE=/tmp/du_resp_debug
- getopts :f: opt
- '[' -z '' ']'
- BIN_DEPS='sed basename date grep stat dd printf mkdir curl'
- CURL_BIN=curl
- for i in '$BIN_DEPS'
- which sed
- '[' 0 -ne 0 ']'
- for i in '$BIN_DEPS'
- which basename
- '[' 0 -ne 0 ']'
- for i in '$BIN_DEPS'
- which date
- '[' 0 -ne 0 ']'
- for i in '$BIN_DEPS'
- which grep
- '[' 0 -ne 0 ']'
- for i in '$BIN_DEPS'
- which stat
- '[' 0 -ne 0 ']'
- for i in '$BIN_DEPS'
- which dd
- '[' 0 -ne 0 ']'
- for i in '$BIN_DEPS'
- which printf
- '[' 0 -ne 0 ']'
- for i in '$BIN_DEPS'
- which mkdir
- '[' 0 -ne 0 ']'
- for i in '$BIN_DEPS'
- which curl
- '[' 0 -ne 0 ']'
- '[' -f /home/pi/.dropbox_uploader ']'
- echo -ne '\n This is the first time you run this script.\n'
  
  This is the first time you run this script.
- echo -ne ' Please open this URL from your Browser, and access using your account:\n\n -> https://www2.dropbox.com/developers/apps\n'
  Please open this URL from your Browser, and access using your account:
  
  -> https://www2.dropbox.com/developers/apps
- echo -ne '\n If you haven'\''t already done, click "Create an App" and fill in the\n'
  
  If you haven't already done, click "Create an App" and fill in the
- echo -ne ' form with the following data:\n\n'
  form with the following data:
- echo -ne '  App name: MyUploader1244320354\n'
  App name: MyUploader1244320354
- echo -ne '  App type: Core\n'
  App type: Core
- echo -ne '  Permission type: App folder or Full Dropbox\n\n'
  Permission type: App folder or Full Dropbox
- echo -ne ' Now, click on the "Create" button.\n\n'
  Now, click on the "Create" button.
- echo -ne ' When your new App is successfully created, please type the\n'
  When your new App is successfully created, please type the
- echo -ne ' App Key, App Secret and the Access level:\n\n'
  App Key, App Secret and the Access level:
- true
- echo -n ' # App key: '
  # App key: + read APPKEY
  xxxxxxxxxxxxxx
- echo -n ' # App secret: '
  # App secret: + read APPSECRET
  xxxxxxxxxxxxx
- echo -n ' # Access level you have chosen, App folder or Full Dropbox [a/f]: '
  # Access level you have chosen, App folder or Full Dropbox [a/f]: + read ACCESS_LEVEL
  a
- '[' a == a ']'
- ACCESS_LEVEL=sandbox
- ACCESS_MSG='App Folder'
- echo -ne '\n > App key is xxxxxxxx, App secret is xxxxxxxxx and Access level is App Folder, it'\''s ok? [y/n]'
  
  > App key is xxxxxxx, App secret is xxxxxxx and Access level is App Folder, it's ok? [y/n]+ read answer
  > y
- '[' y == y ']'
- break
- echo -ne '\n > Token request... '
  
  > Token request... ++ utime
  > +++ date +%s
  > ++ echo 1372256238
- time=1372256238
- curl -s --show-error --globoff -i -o /tmp/du_resp_debug --data 'oauth_consumer_key=xxxxxxxxxx&oauth_signature_method=PLAINTEXT&oauth_signature=xxxxxxxxxxxx%26&oauth_timestamp=1372256238&oauth_nonce=1202' https://api.dropbox.com/1/oauth/request_token
  ++ sed -n 's/oauth_token_secret=([a-z A-Z 0-9]_)._/\1/p' /tmp/du_resp_debug
  sed: can't read /tmp/du_resp_debug: No such file or directory
- OAUTH_TOKEN_SECRET=
  ++ sed -n 's/._oauth_token=([a-z A-Z 0-9]_)/\1/p' /tmp/du_resp_debug
  sed: can't read /tmp/du_resp_debug: No such file or directory
- OAUTH_TOKEN=
- '[' -n '' -a -n '' ']'
- echo -ne ' FAILED\n\n Please, check your App key and secret...\n\n'
  FAILED
  
  Please, check your App key and secret...
- remove_temp_files
- '[' 1 -eq 0 ']'
- exit 1

**Comment by pbn4** [comment]
Is there any solution for the certificates problem?
