### ISSUE TITLE
Problem running from crontab

### ISSUE THREAD

**Issue by sikrip** [andreafabrizi/Dropbox-Uploader#601]
Hello,

I am invoking the uploader script in from a python script with success.

When I run the same script from crontab (I need to have it run at boot) the uploader script behaves as it is running for the first time, like it is unable to reader to configuration.

Any idea what is the problem?

Thanks,
George

**Comment by tjluoma** [comment]
Could be that the crontab job is running as root not your regular user. Might try running `id` to check who it runs as.

**Comment by sikrip** [comment]
My bad, I was running crotab with sudo. It worked when I run it with my user.
