### ISSUE TITLE
Max File Size Limit?

### ISSUE THREAD

**Issue by camwilmot** [andreafabrizi/Dropbox-Uploader#75]
Hello,

Great script.

I'm trying to upload a 60GB file to Dropbox. Is there a max file limit?

I'm getting:

An error occurred requesting /chunked_upload

**Comment by youqingkui** [comment]
Dropbox api 
No more than 200M？

**Comment by andreafabrizi** [comment]
The Dropbox API allows to upload up to 150Mb. If a file is bigger than 150Mb, it's split in more chunks.
