### ISSUE TITLE
Error: this script requires the BASH shell!

### ISSUE THREAD

**Issue by seraphyn** [andreafabrizi/Dropbox-Uploader#78]
And of course I've ;)

chris@ecmbig ~ $ sh dropbox_uploader.sh 
-e Error: this script requires the BASH shell!
chris@ecmbig ~ $ echo $SHELL
/bin/bash
So what could I do?
thanks in advance

**Comment by rubens001** [comment]
I Had the same problem and solved it executing :
bash /payh/dropbox_uploader.sh
tks :-)
